import { createContext, useContext, useState, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navbar
    "nav.contact": "Contacto",
    
    // Hero
    "hero.badge": "Régimen Especial",
    "hero.title": "Optimiza tu Fiscalidad con la Ley Beckham",
    "hero.subtitle": "Tributa solo al 24% durante 6 años. Asesoramiento experto para profesionales internacionales que se trasladan a España.",
    "hero.cta.consult": "Solicitar Consulta Gratuita",
    "hero.cta.requirements": "Ver Requisitos",
    "hero.stat.success": "Tasa de Éxito",
    "hero.stat.experience": "Experiencia",
    "hero.stat.tax": "Tipo Impositivo",
    "hero.stat.years": "años",
    
    // Benefits
    "benefits.eyebrow": "Ventajas Fiscales",
    "benefits.title": "Beneficios Clave de la Ley Beckham",
    "benefits.subtitle": "Optimiza tu carga fiscal al máximo con este régimen especial",
    "benefits.tax.title": "Tipo Impositivo Reducido",
    "benefits.tax.description": "Tributación fija del 24% sobre los rendimientos del trabajo hasta 600.000€ anuales, en lugar del IRPF progresivo que puede llegar al 47%.",
    "benefits.duration.title": "Hasta 6 Años de Beneficios",
    "benefits.duration.description": "Mantén el régimen especial durante el año de cambio de residencia y los 5 años siguientes, con posibilidad de prórroga bajo ciertas condiciones.",
    "benefits.worldwide.title": "Tributación Mundial Limitada",
    "benefits.worldwide.description": "Solo tributas por rentas obtenidas en España. Las rentas del extranjero solo se gravan si exceden 600.000€ anuales.",
    "benefits.security.title": "Seguridad y Legalidad",
    "benefits.security.description": "Régimen legal completamente respaldado por la Agencia Tributaria y utilizado por miles de profesionales cada año.",
    
    // What Is
    "whatIs.eyebrow": "Régimen Especial",
    "whatIs.title": "¿Qué es la Ley Beckham?",
    "whatIs.p1": "La Ley Beckham es el nombre popular del régimen especial de tributación para trabajadores desplazados a España, regulado en el artículo 93 de la Ley del IRPF.",
    "whatIs.p2": "Este régimen permite a profesionales extranjeros que se trasladan a España tributar como no residentes fiscales, con un tipo fijo del 24% sobre sus rendimientos del trabajo, en lugar del IRPF progresivo que puede llegar hasta el 47%.",
    "whatIs.p3": "Establecido en 2005 tras la llegada del futbolista David Beckham al Real Madrid, este régimen busca atraer talento internacional a España ofreciendo ventajas fiscales significativas durante hasta 6 años.",
    
    // Requirements
    "requirements.eyebrow": "Requisitos",
    "requirements.title": "¿Cumples los Requisitos para la Ley Beckham?",
    "requirements.subtitle": "Verifica si puedes acogerte al régimen especial de tributación",
    "requirements.keyLabel": "Requisito Clave",
    "requirements.item1.title": "No haber sido residente fiscal en España",
    "requirements.item1.description": "No haber sido residente fiscal en España en los 10 años anteriores al traslado. Este es el requisito más crítico y debe verificarse cuidadosamente.",
    "requirements.item2.title": "Traslado por motivos laborales",
    "requirements.item2.description": "Debes trasladarte a España para trabajar por cuenta ajena, ser administrador de una empresa, o realizar una actividad empresarial.",
    "requirements.item3.title": "Contrato de trabajo o nombramiento",
    "requirements.item3.description": "Necesitas un contrato laboral con una empresa española o un nombramiento como administrador. Los autónomos que facturen principalmente a España no suelen calificar.",
    "requirements.item4.title": "Solicitud dentro del plazo",
    "requirements.item4.description": "Debes presentar la solicitud dentro de los 6 meses siguientes al inicio de la actividad laboral en España o al cambio de residencia fiscal.",
    "requirements.item5.title": "Mantener las condiciones",
    "requirements.item5.description": "Durante el periodo del régimen especial, debes mantener tu residencia fiscal en España y no perder el vínculo laboral que motivó el traslado.",
    "requirements.cta.title": "¿No estás seguro de cumplir los requisitos?",
    "requirements.cta.description": "Cada caso es único. Solicita una consulta gratuita y analizaremos tu situación específica.",
    "requirements.cta.button": "Consulta Gratuita",
    
    // Profiles
    "profiles.eyebrow": "¿Para quién?",
    "profiles.title": "Perfiles que se Benefician de la Ley Beckham",
    "profiles.subtitle": "Este régimen fiscal especial está diseñado para diversos profesionales internacionales",
    "profiles.executives.title": "Ejecutivos y Directivos",
    "profiles.executives.description": "C-level, directores generales, altos cargos en empresas multinacionales",
    "profiles.executives.badge": "Alta Demanda",
    "profiles.tech.title": "Profesionales Tech",
    "profiles.tech.description": "Ingenieros, developers, CTOs, product managers, data scientists",
    "profiles.tech.badge": "Sector Tech",
    "profiles.financial.title": "Sector Financiero",
    "profiles.financial.description": "Banqueros, traders, analistas financieros, consultores de inversión",
    "profiles.financial.badge": "Finanzas",
    "profiles.consultants.title": "Consultores",
    "profiles.consultants.description": "Consultores estratégicos, auditores, expertos en transformación digital",
    "profiles.consultants.badge": "Consulting",
    "profiles.entrepreneurs.title": "Emprendedores",
    "profiles.entrepreneurs.description": "Fundadores de startups, inversores, business angels que se trasladan",
    "profiles.entrepreneurs.badge": "Startups",
    "profiles.researchers.title": "Investigadores",
    "profiles.researchers.description": "Profesores universitarios, investigadores científicos, expertos académicos",
    "profiles.researchers.badge": "Academia",
    
    // Comparison
    "comparison.eyebrow": "Comparativa Fiscal",
    "comparison.title": "¿Cuánto Puedes Ahorrar con la Ley Beckham?",
    "comparison.subtitle": "Compara la tributación estándar del IRPF con la Ley Beckham según tu nivel de ingresos",
    "comparison.table.income": "Ingresos Anuales",
    "comparison.table.irpf": "IRPF General",
    "comparison.table.beckham": "Ley Beckham",
    "comparison.table.savings": "Ahorro",
    "comparison.irpf.title": "IRPF General",
    "comparison.irpf.point1": "Tramos progresivos del 19% al 47%",
    "comparison.irpf.point2": "Tributación sobre rentas mundiales",
    "comparison.irpf.point3": "Obligaciones de declaración completas",
    "comparison.irpf.point4": "Régimen estándar de residentes",
    "comparison.beckham.title": "Régimen Beckham",
    "comparison.beckham.point1": "Tipo fijo del 24% (simplificado)",
    "comparison.beckham.point2": "Solo rentas españolas hasta 600K€",
    "comparison.beckham.point3": "Menos obligaciones formales",
    "comparison.beckham.point4": "Vigencia hasta 6 años",
    "comparison.disclaimer": "* Cálculos aproximados. La tributación real puede variar según circunstancias personales.",
    
    // Process
    "process.eyebrow": "Proceso Simple y Transparente",
    "process.title": "Cómo Solicitamos la Ley Beckham por Ti",
    "process.subtitle": "Te acompañamos en cada paso del proceso, desde el análisis inicial hasta la aprobación",
    "process.step": "Paso",
    "process.step1.title": "Análisis de Elegibilidad",
    "process.step1.description": "Evaluamos tu situación personal y profesional para confirmar que cumples todos los requisitos del régimen especial",
    "process.step1.duration": "1-2 días",
    "process.step1.detail1": "Revisión de historial fiscal",
    "process.step1.detail2": "Análisis contractual",
    "process.step1.detail3": "Evaluación de residencia",
    "process.step2.title": "Preparación de Documentación",
    "process.step2.description": "Recopilamos y preparamos toda la documentación necesaria para la solicitud ante la Agencia Tributaria",
    "process.step2.duration": "3-5 días",
    "process.step2.detail1": "Contrato de trabajo",
    "process.step2.detail2": "Certificados fiscales",
    "process.step2.detail3": "Modelo 149",
    "process.step2.detail4": "Documentación complementaria",
    "process.step3.title": "Presentación Modelo 149",
    "process.step3.description": "Presentamos telemáticamente tu solicitud ante la AEAT con toda la documentación justificativa",
    "process.step3.duration": "1 día",
    "process.step3.detail1": "Presentación telemática",
    "process.step3.detail2": "Acuse de recibo",
    "process.step3.detail3": "Seguimiento del expediente",
    "process.step4.title": "Seguimiento y Resolución",
    "process.step4.description": "Realizamos el seguimiento del expediente y gestionamos cualquier requerimiento de la Agencia Tributaria",
    "process.step4.duration": "1-3 meses",
    "process.step4.detail1": "Seguimiento continuo",
    "process.step4.detail2": "Atención a requerimientos",
    "process.step4.detail3": "Comunicación con AEAT",
    "process.step5.title": "Aprobación y Optimización",
    "process.step5.description": "Una vez aprobado, te asesoramos en la optimización fiscal continua durante los 6 años del régimen",
    "process.step5.duration": "Continuo",
    "process.step5.detail1": "Planificación fiscal",
    "process.step5.detail2": "Declaraciones anuales",
    "process.step5.detail3": "Asesoramiento continuo",
    "process.cta.title": "Solicita tu Consulta Gratuita Hoy",
    "process.cta.description": "Nuestro equipo de expertos analizará tu caso sin compromiso y te indicará exactamente los pasos a seguir para beneficiarte de la Ley Beckham.",
    "process.cta.button": "Comenzar Mi Solicitud",
    
    // Why Us
    "whyUs.eyebrow": "Expertos en Fiscalidad Internacional",
    "whyUs.title": "Por Qué Confiar en NRRO",
    "whyUs.subtitle": "Más de 25 años de experiencia ayudando a profesionales internacionales",
    "whyUs.stat1.label": "Años de Experiencia",
    "whyUs.stat1.value": "25+",
    "whyUs.stat1.description": "Liderando la fiscalidad internacional en España",
    "whyUs.stat2.label": "Tasa de Éxito",
    "whyUs.stat2.value": "98%",
    "whyUs.stat2.description": "Solicitudes aprobadas por la Agencia Tributaria",
    "whyUs.stat3.label": "Clientes Asesorados",
    "whyUs.stat3.value": "500+",
    "whyUs.stat3.description": "Profesionales de más de 40 países",
    "whyUs.stat4.label": "Confidencialidad",
    "whyUs.stat4.value": "100%",
    "whyUs.stat4.description": "Garantía total de privacidad y seguridad",
    
    // FAQ
    "faq.eyebrow": "Resolvemos tus Dudas",
    "faq.title": "Preguntas Frecuentes sobre la Ley Beckham",
    "faq.subtitle": "Todo lo que necesitas saber sobre el régimen especial de impatriados",
    "faq.q1": "¿Cuánto tiempo tarda la aprobación de la Ley Beckham?",
    "faq.a1": "El plazo habitual de resolución por parte de la Agencia Tributaria es de 1 a 3 meses desde la presentación del Modelo 149. Sin embargo, es importante presentar la solicitud dentro de los 6 meses siguientes al inicio de la actividad laboral en España. En NRRO, agilizamos el proceso asegurándonos de que toda la documentación esté perfecta desde el primer momento, lo que aumenta significativamente las probabilidades de una aprobación rápida.",
    "faq.q2": "¿Puedo solicitar la Ley Beckham si ya estoy trabajando en España?",
    "faq.a2": "Sí, pero solo si no han transcurrido más de 6 meses desde que iniciaste tu actividad laboral en España. Este plazo es improrrogable, por lo que es crucial actuar con rapidez. Si ya superaste este plazo, lamentablemente no podrás acogerte al régimen para tu situación actual, aunque podrías solicitarlo si en el futuro te trasladas nuevamente a España cumpliendo los requisitos.",
    "faq.q3": "¿Qué ocurre después de los 6 años del régimen especial?",
    "faq.a3": "Tras los 6 años (año de llegada + 5 ejercicios fiscales completos), pasarás automáticamente al régimen general del IRPF español, tributando como residente fiscal ordinario. Es importante planificar esta transición con antelación para optimizar tu situación fiscal. En NRRO te acompañamos durante todo el proceso y te ayudamos a preparar la transición al régimen general, explorando otras opciones de optimización fiscal disponibles.",
    "faq.q4": "¿Es compatible con el régimen de autónomos?",
    "faq.a4": "Sí, la Ley Beckham es compatible con trabajadores autónomos o por cuenta propia, siempre que cumplan el resto de requisitos (principalmente, el desplazamiento a España por motivos de trabajo y no haber sido residente fiscal en los 10 años anteriores). Los autónomos pueden beneficiarse del tipo fijo del 24% sobre sus rendimientos de actividades económicas generados en España.",
    "faq.q5": "¿Mi familia también se beneficia de la Ley Beckham?",
    "faq.a5": "La Ley Beckham es de aplicación individual, por lo que tu cónyuge e hijos no se acogen automáticamente al régimen especial. Sin embargo, existen opciones fiscales para optimizar la tributación familiar. Tu cónyuge podría solicitar el régimen si cumple individualmente los requisitos (por ejemplo, si también viene a trabajar a España). En cuanto a los hijos, existen deducciones y beneficios fiscales en el IRPF ordinario que podemos analizar en tu caso concreto.",
    "faq.q6": "¿Tengo que tributar en España por mis rentas mundiales?",
    "faq.a6": "No, esta es una de las grandes ventajas de la Ley Beckham. Bajo este régimen, tributas como no residente fiscal, lo que significa que solo pagas impuestos en España por tus rentas de fuente española (principalmente, tu salario por trabajo en España). Tus dividendos, intereses, ganancias patrimoniales y otras rentas obtenidas fuera de España están exentas hasta ciertos límites, aunque debes declararlas informativamente. Esto supone un ahorro fiscal muy significativo para profesionales con ingresos internacionales.",
    "faq.q7": "¿Qué sucede si me deniegan la solicitud?",
    "faq.a7": "Aunque nuestra tasa de éxito es del 98%, en caso de denegación, podemos recurrir la decisión mediante alegaciones ante la Agencia Tributaria o, si es necesario, por vía judicial. Las causas más comunes de denegación suelen ser documentación incompleta o no cumplir estrictamente con los requisitos. Por eso, en NRRO realizamos un análisis exhaustivo previo y nos aseguramos de que tu solicitud esté perfectamente fundamentada antes de presentarla.",
    "faq.q8": "¿Cuál es el coste de solicitar la Ley Beckham?",
    "faq.a8": "Nuestros honorarios varían según la complejidad del caso, pero ofrecemos presupuestos transparentes sin sorpresas. Considera que el ahorro fiscal que obtendrás durante los 6 años del régimen (que puede superar los 200.000€ en muchos casos) hace que la inversión en asesoramiento profesional sea altamente rentable. Además, ofrecemos una primera consulta gratuita para evaluar tu caso y darte un presupuesto exacto sin compromiso.",
    "faq.cta.text": "¿Tienes más preguntas? Estamos aquí para ayudarte.",
    "faq.cta.button": "Contactar con un Experto",
    
    // Form
    "form.eyebrow": "Consulta Gratuita",
    "form.title": "Solicita tu Análisis de Elegibilidad",
    "form.subtitle": "Completa el formulario y te contactaremos en menos de 24 horas para evaluar tu caso sin compromiso",
    "form.name": "Nombre completo",
    "form.email": "Email",
    "form.phone": "Teléfono",
    "form.country": "País de origen",
    "form.country.placeholder": "Ej: Reino Unido, Francia...",
    "form.jobSituation": "Situación laboral",
    "form.jobSituation.select": "Selecciona...",
    "form.jobSituation.contract": "Contrato de trabajo en España",
    "form.jobSituation.executive": "Directivo/Administrador",
    "form.jobSituation.freelancer": "Autónomo",
    "form.jobSituation.entrepreneur": "Emprendedor/Fundador",
    "form.jobSituation.transfer": "Traslado interno empresa",
    "form.jobSituation.other": "Otro",
    "form.transferDate": "Fecha estimada de traslado",
    "form.transferDate.already": "Ya estoy en España (menos de 6 meses)",
    "form.transferDate.1-3": "En 1-3 meses",
    "form.transferDate.3-6": "En 3-6 meses",
    "form.transferDate.6-12": "En 6-12 meses",
    "form.transferDate.12+": "Más de 12 meses",
    "form.message": "Mensaje o consulta (opcional)",
    "form.message.placeholder": "Cuéntanos más sobre tu situación...",
    "form.privacy": "Acepto la",
    "form.privacy.link": "política de privacidad",
    "form.privacy.text": "y el tratamiento de mis datos personales",
    "form.button": "Solicitar Consulta Gratuita sobre Ley Beckham",
    "form.button.sending": "Enviando...",
    "form.confidential": "100% Confidencial",
    "form.response": "Respuesta en 24h",
    "form.noCommitment": "Sin compromiso",
    "form.footer": "Este formulario es específico para consultas sobre la Ley Beckham. Para otros servicios,",
    "form.footer.link": "visita nuestra página de contacto",
    "form.success.title": "¡Solicitud enviada con éxito!",
    "form.success.description": "Nos pondremos en contacto contigo en menos de 24 horas para analizar tu caso.",
    "form.error.title": "Error al enviar",
    "form.error.description": "Ha ocurrido un error. Por favor, inténtalo de nuevo o contacta por teléfono.",
    "form.validation.name": "El nombre debe tener al menos 2 caracteres",
    "form.validation.email": "Email inválido",
    "form.validation.phone": "Teléfono inválido",
    "form.validation.country": "Selecciona tu país de origen",
    "form.validation.jobSituation": "Selecciona tu situación laboral",
    "form.validation.transferDate": "Indica tu fecha estimada de traslado",
    "form.validation.privacy": "Debes aceptar la política de privacidad",
    
    // Final CTA
    "finalCta.title": "No Pierdas la Oportunidad de Optimizar tu Fiscalidad",
    "finalCta.subtitle": "Los plazos para acogerse a la Ley Beckham son limitados. Solicita tu consulta gratuita hoy y descubre cuánto puedes ahorrar.",
    "finalCta.button": "Solicitar Consulta Gratuita",
    "finalCta.footer": "Respuesta en menos de 24 horas • 100% Confidencial • Sin compromiso",
    
    // SEO Meta
    "seo.title": "Ley Beckham - Asesoría Fiscal para Profesionales Internacionales",
    "seo.description": "Tributa al 24% durante 6 años. Asesoramiento experto en la Ley Beckham para profesionales que se trasladan a España.",
    "seo.keywords": "ley beckham, régimen especial trabajadores desplazados, tributación 24%, fiscalidad internacional españa, asesoría beckham",
  },
  en: {
    // Navbar
    "nav.contact": "Contact",
    
    // Hero
    "hero.badge": "Special Regime",
    "hero.title": "Optimize Your Taxes with Beckham Law",
    "hero.subtitle": "Pay only 24% tax for 6 years. Expert advice for international professionals moving to Spain.",
    "hero.cta.consult": "Request Free Consultation",
    "hero.cta.requirements": "View Requirements",
    "hero.stat.success": "Success Rate",
    "hero.stat.experience": "Experience",
    "hero.stat.tax": "Tax Rate",
    "hero.stat.years": "years",
    
    // Benefits
    "benefits.eyebrow": "Tax Benefits",
    "benefits.title": "Key Benefits of Beckham Law",
    "benefits.subtitle": "Maximize your tax optimization with this special regime",
    "benefits.tax.title": "Reduced Tax Rate",
    "benefits.tax.description": "Fixed 24% taxation on employment income up to €600,000 annually, instead of progressive IRPF rates that can reach 47%.",
    "benefits.duration.title": "Up to 6 Years of Benefits",
    "benefits.duration.description": "Maintain the special regime during the year of residence change and the following 5 years, with possible extension under certain conditions.",
    "benefits.worldwide.title": "Limited Worldwide Taxation",
    "benefits.worldwide.description": "You only pay taxes on income obtained in Spain. Foreign income is only taxed if it exceeds €600,000 annually.",
    "benefits.security.title": "Security and Legality",
    "benefits.security.description": "Legal regime fully backed by the Tax Agency and used by thousands of professionals every year.",
    
    // What Is
    "whatIs.eyebrow": "Special Regime",
    "whatIs.title": "What is the Beckham Law?",
    "whatIs.p1": "The Beckham Law is the popular name for the special tax regime for workers relocated to Spain, regulated in Article 93 of the Personal Income Tax Law.",
    "whatIs.p2": "This regime allows foreign professionals relocating to Spain to be taxed as non-tax residents, with a fixed rate of 24% on their employment income, instead of the progressive IRPF that can reach up to 47%.",
    "whatIs.p3": "Established in 2005 following footballer David Beckham's arrival at Real Madrid, this regime seeks to attract international talent to Spain by offering significant tax advantages for up to 6 years.",
    
    // Requirements
    "requirements.eyebrow": "Requirements",
    "requirements.title": "Do You Meet the Requirements for Beckham Law?",
    "requirements.subtitle": "Verify if you can qualify for the special tax regime",
    "requirements.keyLabel": "Key Requirement",
    "requirements.item1.title": "Not have been a tax resident in Spain",
    "requirements.item1.description": "You must not have been a tax resident in Spain in the 10 years prior to relocation. This is the most critical requirement and must be carefully verified.",
    "requirements.item2.title": "Relocation for employment reasons",
    "requirements.item2.description": "You must relocate to Spain to work as an employee, be a company director, or conduct business activity.",
    "requirements.item3.title": "Employment contract or appointment",
    "requirements.item3.description": "You need an employment contract with a Spanish company or an appointment as director. Self-employed individuals who mainly invoice in Spain typically do not qualify.",
    "requirements.item4.title": "Application within the deadline",
    "requirements.item4.description": "You must submit the application within 6 months following the start of work activity in Spain or the change of tax residence.",
    "requirements.item5.title": "Maintain the conditions",
    "requirements.item5.description": "During the special regime period, you must maintain your tax residence in Spain and not lose the employment relationship that motivated the relocation.",
    "requirements.cta.title": "Not sure if you meet the requirements?",
    "requirements.cta.description": "Each case is unique. Request a free consultation and we'll analyze your specific situation.",
    "requirements.cta.button": "Free Consultation",
    
    // Profiles
    "profiles.eyebrow": "Who is it for?",
    "profiles.title": "Profiles That Benefit from Beckham Law",
    "profiles.subtitle": "This special tax regime is designed for various international professionals",
    "profiles.executives.title": "Executives and Directors",
    "profiles.executives.description": "C-level, general directors, senior positions in multinational companies",
    "profiles.executives.badge": "High Demand",
    "profiles.tech.title": "Tech Professionals",
    "profiles.tech.description": "Engineers, developers, CTOs, product managers, data scientists",
    "profiles.tech.badge": "Tech Sector",
    "profiles.financial.title": "Financial Sector",
    "profiles.financial.description": "Bankers, traders, financial analysts, investment consultants",
    "profiles.financial.badge": "Finance",
    "profiles.consultants.title": "Consultants",
    "profiles.consultants.description": "Strategic consultants, auditors, digital transformation experts",
    "profiles.consultants.badge": "Consulting",
    "profiles.entrepreneurs.title": "Entrepreneurs",
    "profiles.entrepreneurs.description": "Startup founders, investors, business angels relocating",
    "profiles.entrepreneurs.badge": "Startups",
    "profiles.researchers.title": "Researchers",
    "profiles.researchers.description": "University professors, scientific researchers, academic experts",
    "profiles.researchers.badge": "Academia",
    
    // Comparison
    "comparison.eyebrow": "Tax Comparison",
    "comparison.title": "How Much Can You Save with Beckham Law?",
    "comparison.subtitle": "Compare standard IRPF taxation with Beckham Law according to your income level",
    "comparison.table.income": "Annual Income",
    "comparison.table.irpf": "General IRPF",
    "comparison.table.beckham": "Beckham Law",
    "comparison.table.savings": "Savings",
    "comparison.irpf.title": "General IRPF",
    "comparison.irpf.point1": "Progressive brackets from 19% to 47%",
    "comparison.irpf.point2": "Taxation on worldwide income",
    "comparison.irpf.point3": "Full declaration obligations",
    "comparison.irpf.point4": "Standard resident regime",
    "comparison.beckham.title": "Beckham Regime",
    "comparison.beckham.point1": "Fixed 24% rate (simplified)",
    "comparison.beckham.point2": "Only Spanish income up to €600K",
    "comparison.beckham.point3": "Fewer formal obligations",
    "comparison.beckham.point4": "Valid for up to 6 years",
    "comparison.disclaimer": "* Approximate calculations. Actual taxation may vary according to personal circumstances.",
    
    // Process
    "process.eyebrow": "Simple and Transparent Process",
    "process.title": "How We Request Beckham Law for You",
    "process.subtitle": "We accompany you at every step of the process, from initial analysis to approval",
    "process.step": "Step",
    "process.step1.title": "Eligibility Analysis",
    "process.step1.description": "We evaluate your personal and professional situation to confirm you meet all special regime requirements",
    "process.step1.duration": "1-2 days",
    "process.step1.detail1": "Tax history review",
    "process.step1.detail2": "Contract analysis",
    "process.step1.detail3": "Residence evaluation",
    "process.step2.title": "Documentation Preparation",
    "process.step2.description": "We collect and prepare all necessary documentation for the Tax Agency application",
    "process.step2.duration": "3-5 days",
    "process.step2.detail1": "Employment contract",
    "process.step2.detail2": "Tax certificates",
    "process.step2.detail3": "Form 149",
    "process.step2.detail4": "Supplementary documentation",
    "process.step3.title": "Form 149 Submission",
    "process.step3.description": "We submit your application electronically to the AEAT with all supporting documentation",
    "process.step3.duration": "1 day",
    "process.step3.detail1": "Electronic submission",
    "process.step3.detail2": "Receipt acknowledgment",
    "process.step3.detail3": "File tracking",
    "process.step4.title": "Follow-up and Resolution",
    "process.step4.description": "We track the file and manage any requirements from the Tax Agency",
    "process.step4.duration": "1-3 months",
    "process.step4.detail1": "Continuous monitoring",
    "process.step4.detail2": "Handling requirements",
    "process.step4.detail3": "Communication with AEAT",
    "process.step5.title": "Approval and Optimization",
    "process.step5.description": "Once approved, we advise you on continuous tax optimization during the 6 years of the regime",
    "process.step5.duration": "Ongoing",
    "process.step5.detail1": "Tax planning",
    "process.step5.detail2": "Annual declarations",
    "process.step5.detail3": "Ongoing advice",
    "process.cta.title": "Request Your Free Consultation Today",
    "process.cta.description": "Our team of experts will analyze your case without obligation and tell you exactly the steps to follow to benefit from Beckham Law.",
    "process.cta.button": "Start My Application",
    
    // Why Us
    "whyUs.eyebrow": "International Tax Experts",
    "whyUs.title": "Why Trust NRRO",
    "whyUs.subtitle": "Over 25 years of experience helping international professionals",
    "whyUs.stat1.label": "Years of Experience",
    "whyUs.stat1.value": "25+",
    "whyUs.stat1.description": "Leading international taxation in Spain",
    "whyUs.stat2.label": "Success Rate",
    "whyUs.stat2.value": "98%",
    "whyUs.stat2.description": "Applications approved by the Tax Agency",
    "whyUs.stat3.label": "Clients Advised",
    "whyUs.stat3.value": "500+",
    "whyUs.stat3.description": "Professionals from over 40 countries",
    "whyUs.stat4.label": "Confidentiality",
    "whyUs.stat4.value": "100%",
    "whyUs.stat4.description": "Total guarantee of privacy and security",
    
    // FAQ
    "faq.eyebrow": "We Answer Your Questions",
    "faq.title": "Frequently Asked Questions about Beckham Law",
    "faq.subtitle": "Everything you need to know about the special expatriate regime",
    "faq.q1": "How long does Beckham Law approval take?",
    "faq.a1": "The usual resolution period by the Tax Agency is 1 to 3 months from the submission of Form 149. However, it's important to submit the application within 6 months following the start of work activity in Spain. At NRRO, we expedite the process by ensuring all documentation is perfect from the start, significantly increasing the chances of quick approval.",
    "faq.q2": "Can I apply for Beckham Law if I'm already working in Spain?",
    "faq.a2": "Yes, but only if no more than 6 months have elapsed since you started your work activity in Spain. This deadline cannot be extended, so it's crucial to act quickly. If you've already exceeded this period, unfortunately you cannot qualify for the regime for your current situation, although you could apply if you relocate to Spain again in the future meeting the requirements.",
    "faq.q3": "What happens after the 6 years of the special regime?",
    "faq.a3": "After 6 years (arrival year + 5 full tax years), you automatically transition to Spain's general IRPF regime, being taxed as an ordinary tax resident. It's important to plan this transition in advance to optimize your tax situation. At NRRO we accompany you throughout the process and help you prepare for the transition to the general regime, exploring other available tax optimization options.",
    "faq.q4": "Is it compatible with self-employment?",
    "faq.a4": "Yes, Beckham Law is compatible with self-employed workers, provided they meet the other requirements (mainly, relocation to Spain for work reasons and not having been a tax resident in the previous 10 years). Self-employed individuals can benefit from the fixed 24% rate on their economic activity income generated in Spain.",
    "faq.q5": "Does my family also benefit from Beckham Law?",
    "faq.a5": "Beckham Law applies individually, so your spouse and children do not automatically qualify for the special regime. However, there are options to optimize family taxation. Your spouse could apply for the regime if they individually meet the requirements (for example, if they also come to work in Spain). As for children, there are deductions and tax benefits in ordinary IRPF that we can analyze in your specific case.",
    "faq.q6": "Do I have to pay taxes in Spain on my worldwide income?",
    "faq.a6": "No, this is one of the great advantages of Beckham Law. Under this regime, you are taxed as a non-tax resident, which means you only pay taxes in Spain on your Spanish-source income (mainly, your salary for work in Spain). Your dividends, interest, capital gains, and other income obtained outside Spain are exempt up to certain limits, although you must declare them for informational purposes. This represents a very significant tax saving for professionals with international income.",
    "faq.q7": "What happens if my application is denied?",
    "faq.a7": "Although our success rate is 98%, in case of denial, we can appeal the decision through allegations to the Tax Agency or, if necessary, through judicial channels. The most common causes of denial are usually incomplete documentation or not strictly meeting the requirements. That's why at NRRO we conduct an exhaustive prior analysis and ensure your application is perfectly substantiated before submitting it.",
    "faq.q8": "What is the cost of applying for Beckham Law?",
    "faq.a8": "Our fees vary according to case complexity, but we offer transparent quotes with no surprises. Consider that the tax savings you'll obtain during the 6 years of the regime (which can exceed €200,000 in many cases) makes the investment in professional advice highly profitable. Additionally, we offer a first free consultation to evaluate your case and give you an exact quote without obligation.",
    "faq.cta.text": "More questions? We're here to help.",
    "faq.cta.button": "Contact an Expert",
    
    // Form
    "form.eyebrow": "Free Consultation",
    "form.title": "Request Your Eligibility Analysis",
    "form.subtitle": "Complete the form and we'll contact you within 24 hours to evaluate your case without obligation",
    "form.name": "Full name",
    "form.email": "Email",
    "form.phone": "Phone",
    "form.country": "Country of origin",
    "form.country.placeholder": "E.g.: United Kingdom, France...",
    "form.jobSituation": "Employment situation",
    "form.jobSituation.select": "Select...",
    "form.jobSituation.contract": "Employment contract in Spain",
    "form.jobSituation.executive": "Director/Administrator",
    "form.jobSituation.freelancer": "Self-employed",
    "form.jobSituation.entrepreneur": "Entrepreneur/Founder",
    "form.jobSituation.transfer": "Internal company transfer",
    "form.jobSituation.other": "Other",
    "form.transferDate": "Estimated relocation date",
    "form.transferDate.already": "Already in Spain (less than 6 months)",
    "form.transferDate.1-3": "In 1-3 months",
    "form.transferDate.3-6": "In 3-6 months",
    "form.transferDate.6-12": "In 6-12 months",
    "form.transferDate.12+": "More than 12 months",
    "form.message": "Message or inquiry (optional)",
    "form.message.placeholder": "Tell us more about your situation...",
    "form.privacy": "I accept the",
    "form.privacy.link": "privacy policy",
    "form.privacy.text": "and the processing of my personal data",
    "form.button": "Request Free Consultation on Beckham Law",
    "form.button.sending": "Sending...",
    "form.confidential": "100% Confidential",
    "form.response": "Response in 24h",
    "form.noCommitment": "No obligation",
    "form.footer": "This form is specific for Beckham Law inquiries. For other services,",
    "form.footer.link": "visit our contact page",
    "form.success.title": "Request sent successfully!",
    "form.success.description": "We'll contact you within 24 hours to analyze your case.",
    "form.error.title": "Error sending",
    "form.error.description": "An error has occurred. Please try again or contact us by phone.",
    "form.validation.name": "Name must be at least 2 characters",
    "form.validation.email": "Invalid email",
    "form.validation.phone": "Invalid phone",
    "form.validation.country": "Select your country of origin",
    "form.validation.jobSituation": "Select your employment situation",
    "form.validation.transferDate": "Indicate your estimated relocation date",
    "form.validation.privacy": "You must accept the privacy policy",
    
    // Final CTA
    "finalCta.title": "Don't Miss the Opportunity to Optimize Your Taxes",
    "finalCta.subtitle": "Deadlines to qualify for Beckham Law are limited. Request your free consultation today and discover how much you can save.",
    "finalCta.button": "Request Free Consultation",
    "finalCta.footer": "Response in less than 24 hours • 100% Confidential • No obligation",
    
    // SEO Meta
    "seo.title": "Beckham Law - Tax Advisory for International Professionals",
    "seo.description": "Pay only 24% tax for 6 years. Expert advice on Beckham Law for professionals relocating to Spain.",
    "seo.keywords": "beckham law, special regime relocated workers, 24% taxation, international tax spain, beckham advisory",
  }
};
