-- Fase 3: Crear 4 casos de éxito para source_site='audit'
INSERT INTO case_studies (title, slug, hero_title, hero_subtitle, challenge, solution, results_summary, client_name, client_industry, client_size, project_duration, metrics, testimonial_text, testimonial_author, testimonial_position, status, is_featured, display_order, source_site)
VALUES
(
  'TechGlobal Solutions - Auditoría de Cuentas Anuales',
  'techglobal-solutions-auditoria-cuentas-anuales',
  'Auditoría de cuentas anuales para empresa tecnológica en expansión',
  'Cómo completamos la auditoría de una scale-up con operaciones en 3 países en tiempo récord',
  'TechGlobal Solutions, una empresa de software SaaS con sede en Barcelona y filiales en Portugal y Francia, necesitaba completar su primera auditoría de cuentas anuales obligatoria. Los retos principales eran: consolidación de operaciones en tres países con diferentes normativas contables, reconocimiento de ingresos por suscripciones multianuales, y plazos muy ajustados para cumplir con inversores que exigían estados financieros auditados.',
  'Implementamos un enfoque de auditoría basado en riesgos, priorizando las áreas más críticas: reconocimiento de ingresos SaaS y corte de operaciones. Coordinamos equipos locales en los tres países para trabajar en paralelo, utilizando herramientas colaborativas de auditoría. Establecimos procedimientos específicos para verificar el ARR (Annual Recurring Revenue) y el MRR (Monthly Recurring Revenue), métricas clave para los inversores.',
  'Entregamos la opinión de auditoría 2 semanas antes del plazo previsto, lo que permitió a TechGlobal presentar sus estados financieros auditados a tiempo para cerrar su ronda Serie B de 15M€. Además, identificamos mejoras en el control interno de facturación que optimizaron su proceso de cierre mensual.',
  'TechGlobal Solutions',
  'Tecnología / SaaS',
  '150 empleados',
  '6 semanas',
  '[{"label": "Tiempo de entrega", "value": "45 días", "description": "2 semanas antes del plazo"}, {"label": "Ronda de inversión", "value": "15M€", "description": "Serie B cerrada con éxito"}, {"label": "Mejoras identificadas", "value": "12", "description": "Recomendaciones de control interno"}, {"label": "Países coordinados", "value": "3", "description": "España, Portugal, Francia"}]',
  'El equipo de auditoría demostró una comprensión excepcional de nuestro modelo de negocio SaaS. Su rigor técnico y la comunicación fluida fueron clave para cumplir los plazos con nuestros inversores.',
  'Carlos Mendoza',
  'Director Financiero',
  'published',
  true,
  1,
  'audit'
),
(
  'GreenEnergy Corp - Verificación CSRD/ESRS',
  'greenenergy-corp-verificacion-csrd-esrs',
  'Primera verificación ESRS para empresa de energías renovables',
  'Preparación y verificación del primer informe de sostenibilidad bajo la nueva normativa europea',
  'GreenEnergy Corp, operador de parques eólicos y solares con activos valorados en 500M€, debía presentar su primer informe de sostenibilidad bajo los nuevos estándares ESRS de la directiva CSRD. El principal reto era la falta de sistemas de recogida de datos ESG y la complejidad del análisis de doble materialidad requerido por la normativa.',
  'Desarrollamos un plan de trabajo en tres fases: (1) Análisis de brechas y diseño de la matriz de doble materialidad con stakeholders clave, (2) Implementación de sistemas de recogida de datos para los indicadores E1 (Cambio climático) y E5 (Economía circular), prioritarios según materialidad, (3) Verificación con seguridad limitada del informe de sostenibilidad completo.',
  'GreenEnergy fue una de las primeras empresas de su sector en España en publicar un informe de sostenibilidad verificado bajo ESRS, lo que reforzó su posicionamiento ante inversores institucionales con mandatos ESG y facilitó la obtención de financiación verde.',
  'GreenEnergy Corp',
  'Energías Renovables',
  '85 empleados',
  '4 meses',
  '[{"label": "Indicadores ESRS", "value": "127", "description": "Divulgaciones verificadas"}, {"label": "Stakeholders consultados", "value": "45", "description": "En proceso de materialidad"}, {"label": "Financiación verde obtenida", "value": "80M€", "description": "Bono verde emitido"}, {"label": "Rating ESG", "value": "A", "description": "Mejora desde BBB"}]',
  'Nos prepararon para el cumplimiento de CSRD antes que muchos de nuestros competidores. Su experiencia en verificación ESG y el conocimiento del sector energético fueron determinantes.',
  'Elena Vázquez',
  'Directora de Sostenibilidad',
  'published',
  true,
  2,
  'audit'
),
(
  'Inversiones Mediterráneo - Due Diligence M&A',
  'inversiones-mediterraneo-due-diligence-ma',
  'Due Diligence financiera para adquisición en sector industrial',
  'Cómo protegimos una inversión de 25M€ identificando contingencias ocultas',
  'Inversiones Mediterráneo, fondo de private equity especializado en mid-market, estaba evaluando la adquisición de una empresa industrial con facturación de 40M€. Necesitaban una due diligence financiera exhaustiva en un plazo de 4 semanas para tomar la decisión de inversión y negociar el precio final.',
  'Movilizamos un equipo especializado que realizó: análisis de calidad de resultados (Quality of Earnings) con normalización del EBITDA, revisión profunda de la posición financiera neta incluyendo deuda oculta, análisis de working capital y sus tendencias, e identificación de contingencias fiscales, laborales y medioambientales. Utilizamos análisis de datos para detectar anomalías en transacciones.',
  'Identificamos contingencias por valor de 2,3M€ no reveladas inicialmente, incluyendo un litigio laboral oculto y provisiones insuficientes por garantías de producto. Esto permitió renegociar el precio de compra y establecer mecanismos de protección en el SPA (escrow y cláusulas de indemnización).',
  'Inversiones Mediterráneo',
  'Private Equity',
  'Fondo mid-market',
  '4 semanas',
  '[{"label": "Contingencias detectadas", "value": "2,3M€", "description": "Ajuste en precio de compra"}, {"label": "Ahorro para el comprador", "value": "1,8M€", "description": "Renegociación del precio"}, {"label": "Ajustes al EBITDA", "value": "8", "description": "Normalizaciones identificadas"}, {"label": "Días de entrega", "value": "21", "description": "Antes del deadline"}]',
  'La due diligence fue decisiva para nuestra operación. El equipo detectó contingencias que habrían supuesto un problema grave post-adquisición. Profesionalidad y rigor excepcionales.',
  'Miguel Ángel Torres',
  'Managing Partner',
  'published',
  true,
  3,
  'audit'
),
(
  'Fundación Solidaria BCN - Auditoría de Entidad No Lucrativa',
  'fundacion-solidaria-bcn-auditoria-enl',
  'Auditoría y justificación de subvenciones para fundación social',
  'Garantizando la transparencia y el cumplimiento normativo de una ENL con múltiples financiadores',
  'Fundación Solidaria BCN, entidad dedicada a la inclusión social con un presupuesto anual de 3M€, necesitaba auditar sus cuentas anuales y justificar 8 subvenciones de diferentes administraciones públicas. El reto principal era la complejidad de imputar correctamente gastos compartidos a múltiples proyectos subvencionados.',
  'Diseñamos un enfoque integral que combinó la auditoría de cuentas anuales según el plan contable de ENL con la emisión de informes específicos de justificación para cada subvención. Implementamos un sistema de imputación de costes compartidos y ayudamos a la fundación a mejorar su documentación soporte.',
  'La fundación justificó el 100% de sus subvenciones sin incidencias, evitando cualquier riesgo de reintegro. Además, nuestras recomendaciones de control interno mejoraron la eficiencia administrativa, reduciendo el tiempo de cierre mensual en un 40%.',
  'Fundación Solidaria BCN',
  'Tercer Sector / ONG',
  '45 empleados + 120 voluntarios',
  '3 meses',
  '[{"label": "Subvenciones justificadas", "value": "8", "description": "Sin ninguna incidencia"}, {"label": "Importe justificado", "value": "2,1M€", "description": "100% aprobado"}, {"label": "Reducción tiempo cierre", "value": "40%", "description": "Mejora en procesos"}, {"label": "Reintegros evitados", "value": "0€", "description": "Cero incidencias"}]',
  'Entendieron perfectamente las particularidades del tercer sector. La tranquilidad de saber que nuestras subvenciones están correctamente justificadas no tiene precio.',
  'Ana Belén Ruiz',
  'Directora Ejecutiva',
  'published',
  true,
  4,
  'audit'
);