-- Insert 6 sample case studies for the international site
INSERT INTO public.case_studies (
  slug, slug_en, title, title_en, client_name, client_industry, client_size, project_duration, primary_service,
  hero_title, hero_title_en, hero_subtitle, hero_subtitle_en, hero_image_url,
  challenge, challenge_en, solution, solution_en, results_summary, results_summary_en,
  metrics, testimonial_text, testimonial_text_en, testimonial_author, testimonial_position,
  tags, status, source_site, is_featured, display_order, published_at
) VALUES
-- 1. UK SaaS Company (Featured)
(
  'uk-saas-expansion-spain', 'uk-saas-expansion-spain',
  'UK SaaS Company Establishes European Hub in Barcelona', 'UK SaaS Company Establishes European Hub in Barcelona',
  'TechFlow Solutions', 'Technology', '50-200 employees', '3 months', 'Company Formation',
  'UK SaaS Company Establishes European Hub in Barcelona', 'UK SaaS Company Establishes European Hub in Barcelona',
  'Complete company formation and tax optimization for a fast-growing UK technology company', 'Complete company formation and tax optimization for a fast-growing UK technology company',
  'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200',
  'TechFlow Solutions needed to establish a European presence post-Brexit while optimizing their tax structure and ensuring compliance across multiple jurisdictions.',
  'TechFlow Solutions needed to establish a European presence post-Brexit while optimizing their tax structure and ensuring compliance across multiple jurisdictions.',
  'We structured a Spanish SL as their European headquarters, implemented Ley Beckham for relocated executives, and established transfer pricing agreements with the UK parent company.',
  'We structured a Spanish SL as their European headquarters, implemented Ley Beckham for relocated executives, and established transfer pricing agreements with the UK parent company.',
  'Successfully established Barcelona hub with 40% tax savings for relocated executives and full EU market access.',
  'Successfully established Barcelona hub with 40% tax savings for relocated executives and full EU market access.',
  '[{"label": "Tax Savings", "value": "40%", "description": "Reduction in executive tax burden"}, {"label": "Time to Market", "value": "8 weeks", "description": "From decision to operational"}, {"label": "Employees Relocated", "value": "12", "description": "Under Ley Beckham regime"}]'::jsonb,
  'NRRO made our Spanish expansion seamless. Their expertise in both UK and Spanish regulations was invaluable.',
  'NRRO made our Spanish expansion seamless. Their expertise in both UK and Spanish regulations was invaluable.',
  'James Mitchell', 'CEO, TechFlow Solutions',
  ARRAY['company-formation', 'ley-beckham', 'technology', 'uk'],
  'published', 'int', true, 1, NOW()
),
-- 2. German Industrial Group
(
  'german-industrial-acquisition', 'german-industrial-acquisition',
  'German Industrial Group Acquires Spanish Manufacturer', 'German Industrial Group Acquires Spanish Manufacturer',
  'Deutsche Industrie GmbH', 'Manufacturing', '500+ employees', '6 months', 'M&A Advisory',
  'German Industrial Group Acquires Spanish Manufacturer', 'German Industrial Group Acquires Spanish Manufacturer',
  'Cross-border M&A transaction with complex due diligence and post-merger integration', 'Cross-border M&A transaction with complex due diligence and post-merger integration',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200',
  'Deutsche Industrie sought to acquire a Spanish automotive parts manufacturer but faced complex labor obligations, environmental liabilities, and valuation challenges.',
  'Deutsche Industrie sought to acquire a Spanish automotive parts manufacturer but faced complex labor obligations, environmental liabilities, and valuation challenges.',
  'We conducted comprehensive legal and tax due diligence, negotiated deal protections, structured the acquisition for tax efficiency, and managed post-merger integration of 200+ employees.',
  'We conducted comprehensive legal and tax due diligence, negotiated deal protections, structured the acquisition for tax efficiency, and managed post-merger integration of 200+ employees.',
  'Completed €45M acquisition with identified savings of €2.3M in contingent liabilities and optimized holding structure.',
  'Completed €45M acquisition with identified savings of €2.3M in contingent liabilities and optimized holding structure.',
  '[{"label": "Deal Value", "value": "€45M", "description": "Transaction size"}, {"label": "Savings Identified", "value": "€2.3M", "description": "In contingent liabilities"}, {"label": "Employees Integrated", "value": "200+", "description": "Seamless transition"}]'::jsonb,
  'The NRRO team identified risks we would have missed and structured the deal to protect our interests perfectly.',
  'The NRRO team identified risks we would have missed and structured the deal to protect our interests perfectly.',
  'Hans Weber', 'CFO, Deutsche Industrie GmbH',
  ARRAY['m&a', 'manufacturing', 'germany', 'due-diligence'],
  'published', 'int', false, 2, NOW()
),
-- 3. US Private Equity Fund
(
  'us-pe-spanish-platform', 'us-pe-spanish-platform',
  'US Private Equity Fund Structures Spanish Platform', 'US Private Equity Fund Structures Spanish Platform',
  'Atlantic Capital Partners', 'Financial Services', 'AUM $2B+', '4 months', 'Corporate Structuring',
  'US Private Equity Fund Structures Spanish Platform', 'US Private Equity Fund Structures Spanish Platform',
  'Multi-jurisdictional holding structure for European investments', 'Multi-jurisdictional holding structure for European investments',
  'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200',
  'Atlantic Capital needed an efficient structure for acquiring and managing multiple Spanish portfolio companies while optimizing for US tax reporting requirements.',
  'Atlantic Capital needed an efficient structure for acquiring and managing multiple Spanish portfolio companies while optimizing for US tax reporting requirements.',
  'We designed a Luxembourg-Spain holding structure, established management company arrangements, and implemented carried interest schemes compliant with both US and Spanish regulations.',
  'We designed a Luxembourg-Spain holding structure, established management company arrangements, and implemented carried interest schemes compliant with both US and Spanish regulations.',
  'Created tax-efficient platform enabling 5 acquisitions with streamlined reporting and optimized exit structure.',
  'Created tax-efficient platform enabling 5 acquisitions with streamlined reporting and optimized exit structure.',
  '[{"label": "Portfolio Companies", "value": "5", "description": "Acquisitions completed"}, {"label": "Structure Efficiency", "value": "15%", "description": "Improved IRR on exits"}, {"label": "Compliance", "value": "100%", "description": "US-Spain treaty optimization"}]'::jsonb,
  'NRRO understands the complexities of cross-border PE structures better than any firm we have worked with in Europe.',
  'NRRO understands the complexities of cross-border PE structures better than any firm we have worked with in Europe.',
  'Sarah Chen', 'Managing Partner, Atlantic Capital',
  ARRAY['private-equity', 'corporate-structuring', 'usa', 'holding-company'],
  'published', 'int', false, 3, NOW()
),
-- 4. French Luxury Brand
(
  'french-luxury-ley-beckham', 'french-luxury-ley-beckham',
  'French Luxury Brand Relocates Leadership to Spain', 'French Luxury Brand Relocates Leadership to Spain',
  'Maison Élégance', 'Retail', '1000+ employees globally', '2 months', 'Ley Beckham',
  'French Luxury Brand Relocates Leadership to Spain', 'French Luxury Brand Relocates Leadership to Spain',
  'Executive relocation with Ley Beckham tax optimization and employment structuring', 'Executive relocation with Ley Beckham tax optimization and employment structuring',
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200',
  'Maison Élégance wanted to relocate their Southern European leadership team to Barcelona but needed to optimize tax burden and structure compliant employment arrangements.',
  'Maison Élégance wanted to relocate their Southern European leadership team to Barcelona but needed to optimize tax burden and structure compliant employment arrangements.',
  'We secured Ley Beckham status for 8 executives, structured their compensation packages, established the Spanish branch operations, and coordinated with French authorities on social security.',
  'We secured Ley Beckham status for 8 executives, structured their compensation packages, established the Spanish branch operations, and coordinated with French authorities on social security.',
  'Relocated leadership team with average 35% reduction in personal tax burden and full social security coordination.',
  'Relocated leadership team with average 35% reduction in personal tax burden and full social security coordination.',
  '[{"label": "Executives Relocated", "value": "8", "description": "All under Ley Beckham"}, {"label": "Tax Reduction", "value": "35%", "description": "Average personal tax savings"}, {"label": "Time to Approval", "value": "6 weeks", "description": "Ley Beckham applications"}]'::jsonb,
  'The tax savings for our team exceeded expectations, and the process was handled with the discretion our brand requires.',
  'The tax savings for our team exceeded expectations, and the process was handled with the discretion our brand requires.',
  'Marie Dubois', 'HR Director, Maison Élégance',
  ARRAY['ley-beckham', 'retail', 'france', 'executive-relocation'],
  'published', 'int', false, 4, NOW()
),
-- 5. Swedish E-commerce
(
  'swedish-ecommerce-spain', 'swedish-ecommerce-spain',
  'Swedish E-commerce Giant Launches Spanish Operations', 'Swedish E-commerce Giant Launches Spanish Operations',
  'NordicShop AB', 'E-commerce', '200-500 employees', '4 months', 'Subsidiary Setup',
  'Swedish E-commerce Giant Launches Spanish Operations', 'Swedish E-commerce Giant Launches Spanish Operations',
  'Full subsidiary establishment with warehouse operations and local hiring', 'Full subsidiary establishment with warehouse operations and local hiring',
  'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200',
  'NordicShop needed to establish Spanish operations quickly to meet growing demand, including warehouse facilities, local employment, and VAT compliance for cross-border sales.',
  'NordicShop needed to establish Spanish operations quickly to meet growing demand, including warehouse facilities, local employment, and VAT compliance for cross-border sales.',
  'We incorporated the Spanish subsidiary, negotiated warehouse lease terms, established payroll and HR systems for 45 employees, and implemented VAT OSS compliance for EU-wide sales.',
  'We incorporated the Spanish subsidiary, negotiated warehouse lease terms, established payroll and HR systems for 45 employees, and implemented VAT OSS compliance for EU-wide sales.',
  'Launched Spanish operations in 10 weeks with full compliance, enabling 200% growth in Southern European sales.',
  'Launched Spanish operations in 10 weeks with full compliance, enabling 200% growth in Southern European sales.',
  '[{"label": "Launch Time", "value": "10 weeks", "description": "Concept to operational"}, {"label": "Local Hires", "value": "45", "description": "Employees onboarded"}, {"label": "Sales Growth", "value": "200%", "description": "Southern Europe region"}]'::jsonb,
  'NRRO handled everything from company formation to hiring our first 45 employees. They became an extension of our team.',
  'NRRO handled everything from company formation to hiring our first 45 employees. They became an extension of our team.',
  'Erik Lindqvist', 'COO, NordicShop AB',
  ARRAY['subsidiary', 'e-commerce', 'sweden', 'hiring'],
  'published', 'int', false, 5, NOW()
),
-- 6. Swiss Family Office
(
  'swiss-family-office-real-estate', 'swiss-family-office-real-estate',
  'Swiss Family Office Invests in Spanish Real Estate Portfolio', 'Swiss Family Office Invests in Spanish Real Estate Portfolio',
  'Geneva Wealth Partners', 'Real Estate', 'AUM €500M+', '5 months', 'Investment Structuring',
  'Swiss Family Office Invests in Spanish Real Estate Portfolio', 'Swiss Family Office Invests in Spanish Real Estate Portfolio',
  'Tax-efficient real estate investment structure with succession planning', 'Tax-efficient real estate investment structure with succession planning',
  'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200',
  'Geneva Wealth Partners sought to invest €30M in Spanish commercial real estate while optimizing for wealth tax, succession planning, and potential exit scenarios.',
  'Geneva Wealth Partners sought to invest €30M in Spanish commercial real estate while optimizing for wealth tax, succession planning, and potential exit scenarios.',
  'We structured investments through a Spanish SOCIMI (REIT equivalent), implemented family governance protocols, and established succession mechanisms compliant with Swiss-Spanish treaty provisions.',
  'We structured investments through a Spanish SOCIMI (REIT equivalent), implemented family governance protocols, and established succession mechanisms compliant with Swiss-Spanish treaty provisions.',
  'Deployed €30M across 5 properties with optimized tax treatment and clear succession pathway for next generation.',
  'Deployed €30M across 5 properties with optimized tax treatment and clear succession pathway for next generation.',
  '[{"label": "Investment", "value": "€30M", "description": "Total deployed capital"}, {"label": "Properties", "value": "5", "description": "Commercial assets acquired"}, {"label": "Tax Efficiency", "value": "12%", "description": "Effective rate achieved"}]'::jsonb,
  'NRRO understood both our investment objectives and family dynamics. The structure they created will serve our family for generations.',
  'NRRO understood both our investment objectives and family dynamics. The structure they created will serve our family for generations.',
  'Philippe Rochat', 'Principal, Geneva Wealth Partners',
  ARRAY['real-estate', 'family-office', 'switzerland', 'succession'],
  'published', 'int', false, 6, NOW()
);