-- =============================================
-- SUBSERVICIOS DE AUDITORÍA DE SUBVENCIONES
-- =============================================

-- 1. Auditoría I+D+i e Innovación (CDTI, Torres Quevedo, Neotec)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría de Subvenciones I+D+i',
  'R&D&I Grant Audit',
  'Auditoria de Subvencions R+D+i',
  'auditoria-subvenciones-idi',
  'rdi-grant-audit',
  'auditoria-subvencions-rdi',
  'Auditoría especializada en la justificación de proyectos de I+D+i financiados por CDTI, programas Neotec, Torres Quevedo, y ayudas autonómicas de innovación. Verificamos la elegibilidad de gastos, el cumplimiento de hitos técnicos y la correcta imputación de costes de personal investigador.',
  'Specialized audit for R&D&I project justification funded by CDTI, Neotec programs, Torres Quevedo, and regional innovation grants. We verify expense eligibility, technical milestone compliance and correct attribution of researcher personnel costs.',
  'Auditoria especialitzada en la justificació de projectes de R+D+i finançats per CDTI, programes Neotec, Torres Quevedo, i ajudes autonòmiques d''innovació. Verifiquem l''elegibilitat de despeses, el compliment de fites tècniques i la correcta imputació de costos de personal investigador.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'Lightbulb',
  ARRAY['Revisión de elegibilidad de gastos de personal investigador', 'Verificación de subcontrataciones y colaboraciones externas', 'Control de costes indirectos y overheads', 'Revisión de hitos técnicos vs. memoria económica', 'Verificación de no doble financiación', 'Informe para cuenta justificativa CDTI'],
  ARRAY['Researcher personnel expense eligibility review', 'Subcontracting and external collaboration verification', 'Indirect costs and overheads control', 'Technical milestones vs economic report review', 'No double funding verification', 'CDTI justification account report'],
  ARRAY['Revisió d''elegibilitat de despeses de personal investigador', 'Verificació de subcontractacions i col·laboracions externes', 'Control de costos indirectes i overheads', 'Revisió de fites tècniques vs. memòria econòmica', 'Verificació de no doble finançament', 'Informe per a compte justificatiu CDTI'],
  ARRAY['Empresas tecnológicas y startups', 'Centros de investigación', 'Empresas industriales innovadoras', 'Spin-offs universitarias', 'Pymes con proyectos de I+D'],
  ARRAY['Technology companies and startups', 'Research centers', 'Innovative industrial companies', 'University spin-offs', 'SMEs with R&D projects'],
  ARRAY['Empreses tecnològiques i startups', 'Centres de recerca', 'Empreses industrials innovadores', 'Spin-offs universitàries', 'Pimes amb projectes de R+D'],
  'Auditoría Subvenciones I+D+i | CDTI, Neotec, Torres Quevedo',
  'R&D&I Grant Audit | CDTI, Neotec, Torres Quevedo',
  'Auditoria Subvencions R+D+i | CDTI, Neotec, Torres Quevedo',
  'Expertos en auditoría de proyectos CDTI, Neotec y Torres Quevedo. Verificamos la elegibilidad de gastos y cumplimiento de bases. 99% tasa de aprobación.',
  'Experts in CDTI, Neotec and Torres Quevedo project auditing. We verify expense eligibility and compliance. 99% approval rate.',
  'Experts en auditoria de projectes CDTI, Neotec i Torres Quevedo. Verifiquem l''elegibilitat de despeses i compliment de bases. 99% taxa d''aprovació.',
  201, true, 'audit'
);

-- 2. Auditoría Energía y Sostenibilidad (IDAE, MOVES, PREE)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría de Subvenciones Energéticas',
  'Energy Grant Audit',
  'Auditoria de Subvencions Energètiques',
  'auditoria-subvenciones-energia',
  'energy-grant-audit',
  'auditoria-subvencions-energia',
  'Auditoría de justificación de ayudas IDAE, programas MOVES, PREE y subvenciones de rehabilitación energética MIVAU. Verificamos el cumplimiento de requisitos técnicos, la correcta ejecución de instalaciones y el cumplimiento del principio DNSH obligatorio.',
  'Justification audit for IDAE grants, MOVES programs, PREE and MIVAU energy rehabilitation subsidies. We verify technical requirements compliance, correct installation execution and mandatory DNSH principle compliance.',
  'Auditoria de justificació d''ajudes IDAE, programes MOVES, PREE i subvencions de rehabilitació energètica MIVAU. Verifiquem el compliment de requisits tècnics, la correcta execució d''instal·lacions i el compliment del principi DNSH obligatori.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'Zap',
  ARRAY['Verificación de certificados energéticos pre/post', 'Control de facturas de instalaciones y equipos', 'Revisión de cumplimiento DNSH medioambiental', 'Verificación de ahorro energético declarado', 'Control de plazos de ejecución', 'Informe para justificación IDAE/CCAA'],
  ARRAY['Pre/post energy certificate verification', 'Installation and equipment invoice control', 'Environmental DNSH compliance review', 'Declared energy savings verification', 'Execution deadline control', 'IDAE/Regional justification report'],
  ARRAY['Verificació de certificats energètics pre/post', 'Control de factures d''instal·lacions i equips', 'Revisió de compliment DNSH mediambiental', 'Verificació d''estalvi energètic declarat', 'Control de terminis d''execució', 'Informe per a justificació IDAE/CCAA'],
  ARRAY['Empresas industriales', 'Comunidades de propietarios', 'Hoteles y sector turístico', 'Empresas de transporte', 'Administraciones locales'],
  ARRAY['Industrial companies', 'Property owner communities', 'Hotels and tourism sector', 'Transport companies', 'Local administrations'],
  ARRAY['Empreses industrials', 'Comunitats de propietaris', 'Hotels i sector turístic', 'Empreses de transport', 'Administracions locals'],
  'Auditoría Subvenciones IDAE, MOVES, PREE | Eficiencia Energética',
  'IDAE, MOVES, PREE Grant Audit | Energy Efficiency',
  'Auditoria Subvencions IDAE, MOVES, PREE | Eficiència Energètica',
  'Auditoría especializada en subvenciones energéticas IDAE, MOVES y PREE. Verificamos DNSH y requisitos técnicos. Evite reintegros.',
  'Specialized audit for IDAE, MOVES and PREE energy grants. We verify DNSH and technical requirements. Avoid reimbursements.',
  'Auditoria especialitzada en subvencions energètiques IDAE, MOVES i PREE. Verifiquem DNSH i requisits tècnics. Eviteu reintegraments.',
  202, true, 'audit'
);

-- 3. Auditoría Digitalización (Kit Digital, CE Implementa)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría de Subvenciones de Digitalización',
  'Digitalization Grant Audit',
  'Auditoria de Subvencions de Digitalització',
  'auditoria-subvenciones-digitalizacion',
  'digitalization-grant-audit',
  'auditoria-subvencions-digitalitzacio',
  'Auditoría de justificación de ayudas Kit Digital, CE Implementa, Activa Industria 4.0 y programas de transformación digital. Verificamos la correcta implantación de soluciones TIC, el cumplimiento de niveles de servicio y la documentación técnica requerida.',
  'Justification audit for Kit Digital, CE Implementa, Activa Industry 4.0 grants and digital transformation programs. We verify correct ICT solution implementation, service level compliance and required technical documentation.',
  'Auditoria de justificació d''ajudes Kit Digital, CE Implementa, Activa Indústria 4.0 i programes de transformació digital. Verifiquem la correcta implantació de solucions TIC, el compliment de nivells de servei i la documentació tècnica requerida.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'Laptop',
  ARRAY['Verificación de implantación efectiva de soluciones', 'Control de facturación de agentes digitalizadores', 'Revisión de acuerdos de nivel de servicio', 'Verificación de mantenimiento y soporte', 'Control de plazos de ejecución y prórrogas', 'Documentación para cierre de expediente'],
  ARRAY['Effective solution implementation verification', 'Digitalizing agent billing control', 'Service level agreement review', 'Maintenance and support verification', 'Execution deadlines and extensions control', 'File closure documentation'],
  ARRAY['Verificació d''implantació efectiva de solucions', 'Control de facturació d''agents digitalitzadors', 'Revisió d''acords de nivell de servei', 'Verificació de manteniment i suport', 'Control de terminis d''execució i pròrrogues', 'Documentació per a tancament d''expedient'],
  ARRAY['Pymes y micropymes', 'Autónomos', 'Comercios minoristas', 'Empresas de servicios', 'Empresas industriales'],
  ARRAY['SMEs and micro-SMEs', 'Self-employed', 'Retail shops', 'Service companies', 'Industrial companies'],
  ARRAY['Pimes i micropimes', 'Autònoms', 'Comerços minoristes', 'Empreses de serveis', 'Empreses industrials'],
  'Auditoría Kit Digital, CE Implementa | Digitalización',
  'Kit Digital, CE Implementa Audit | Digitalization',
  'Auditoria Kit Digital, CE Implementa | Digitalització',
  'Auditoría especializada en Kit Digital y programas de digitalización. Verificamos implantación TIC y cumplimiento de bases.',
  'Specialized audit for Kit Digital and digitalization programs. We verify ICT implementation and compliance.',
  'Auditoria especialitzada en Kit Digital i programes de digitalització. Verifiquem implantació TIC i compliment de bases.',
  203, true, 'audit'
);

-- 4. Auditoría FUNDAE (Formación Bonificada)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría FUNDAE y Formación Bonificada',
  'FUNDAE and Subsidized Training Audit',
  'Auditoria FUNDAE i Formació Bonificada',
  'auditoria-fundae',
  'fundae-training-audit',
  'auditoria-fundae',
  'Auditoría de créditos de formación bonificada FUNDAE, contratos de formación en alternancia y programas de prácticas bonificadas. Verificamos la correcta imputación de costes, el cumplimiento de requisitos formativos y la documentación de control de asistencia.',
  'Audit of FUNDAE subsidized training credits, alternating training contracts and subsidized internship programs. We verify correct cost attribution, training requirements compliance and attendance control documentation.',
  'Auditoria de crèdits de formació bonificada FUNDAE, contractes de formació en alternança i programes de pràctiques bonificades. Verifiquem la correcta imputació de costos, el compliment de requisits formatius i la documentació de control d''assistència.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'GraduationCap',
  ARRAY['Revisión de créditos disponibles y consumidos', 'Verificación de costes directos e indirectos', 'Control de documentación formativa', 'Revisión de controles de asistencia', 'Verificación de requisitos de formadores', 'Informe ante inspección FUNDAE'],
  ARRAY['Available and consumed credits review', 'Direct and indirect costs verification', 'Training documentation control', 'Attendance controls review', 'Trainer requirements verification', 'FUNDAE inspection report'],
  ARRAY['Revisió de crèdits disponibles i consumits', 'Verificació de costos directes i indirectes', 'Control de documentació formativa', 'Revisió de controls d''assistència', 'Verificació de requisits de formadors', 'Informe davant inspecció FUNDAE'],
  ARRAY['Grandes empresas', 'Pymes con planes de formación', 'Grupos empresariales', 'Entidades organizadoras', 'Centros de formación'],
  ARRAY['Large companies', 'SMEs with training plans', 'Business groups', 'Organizing entities', 'Training centers'],
  ARRAY['Grans empreses', 'Pimes amb plans de formació', 'Grups empresarials', 'Entitats organitzadores', 'Centres de formació'],
  'Auditoría FUNDAE | Formación Bonificada Empresas',
  'FUNDAE Audit | Subsidized Business Training',
  'Auditoria FUNDAE | Formació Bonificada Empreses',
  'Auditoría de formación bonificada FUNDAE. Verificamos elegibilidad de costes y cumplimiento ante posibles inspecciones.',
  'FUNDAE subsidized training audit. We verify cost eligibility and compliance for potential inspections.',
  'Auditoria de formació bonificada FUNDAE. Verifiquem elegibilitat de costos i compliment davant possibles inspeccions.',
  204, true, 'audit'
);

-- 5. Auditoría Fondos Europeos (FEDER, FSE+, PRTR, Interreg)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría de Fondos Europeos',
  'European Funds Audit',
  'Auditoria de Fons Europeus',
  'auditoria-fondos-europeos',
  'european-funds-audit',
  'auditoria-fons-europeus',
  'Auditoría especializada en la justificación de fondos estructurales FEDER, FSE+, fondos PRTR NextGeneration EU e Interreg. Verificamos el cumplimiento de la normativa comunitaria, el principio DNSH, las declaraciones DACI y la contabilidad separada obligatoria.',
  'Specialized audit for FEDER structural funds, ESF+, PRTR NextGeneration EU funds and Interreg justification. We verify EU regulatory compliance, DNSH principle, DACI declarations and mandatory separate accounting.',
  'Auditoria especialitzada en la justificació de fons estructurals FEDER, FSE+, fons PRTR NextGeneration EU i Interreg. Verifiquem el compliment de la normativa comunitària, el principi DNSH, les declaracions DACI i la comptabilitat separada obligatòria.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'Globe',
  ARRAY['Verificación de cumplimiento normativa UE', 'Control de principio DNSH obligatorio', 'Revisión de declaraciones DACI', 'Verificación de contabilidad separada', 'Control de elegibilidad temporal y geográfica', 'Informe para autoridad de gestión'],
  ARRAY['EU regulatory compliance verification', 'Mandatory DNSH principle control', 'DACI declarations review', 'Separate accounting verification', 'Temporal and geographic eligibility control', 'Management authority report'],
  ARRAY['Verificació de compliment normativa UE', 'Control de principi DNSH obligatori', 'Revisió de declaracions DACI', 'Verificació de comptabilitat separada', 'Control d''elegibilitat temporal i geogràfica', 'Informe per a autoritat de gestió'],
  ARRAY['Administraciones públicas', 'Entidades sin ánimo de lucro', 'Empresas beneficiarias FEDER', 'Consorcios transfronterizos', 'Universidades y centros de investigación'],
  ARRAY['Public administrations', 'Non-profit entities', 'FEDER beneficiary companies', 'Cross-border consortia', 'Universities and research centers'],
  ARRAY['Administracions públiques', 'Entitats sense ànim de lucre', 'Empreses beneficiàries FEDER', 'Consorcis transfronterers', 'Universitats i centres de recerca'],
  'Auditoría FEDER, FSE+, PRTR NextGen | Fondos Europeos',
  'FEDER, ESF+, PRTR NextGen Audit | European Funds',
  'Auditoria FEDER, FSE+, PRTR NextGen | Fons Europeus',
  'Expertos en auditoría de fondos europeos: FEDER, FSE+, PRTR NextGeneration. Verificamos DNSH, DACI y contabilidad separada.',
  'Experts in European funds audit: FEDER, ESF+, PRTR NextGeneration. We verify DNSH, DACI and separate accounting.',
  'Experts en auditoria de fons europeus: FEDER, FSE+, PRTR NextGeneration. Verifiquem DNSH, DACI i comptabilitat separada.',
  205, true, 'audit'
);

-- 6. Auditoría Ayudas Autonómicas (ACCIÓ, IVACE, SPRI, ICEX)
INSERT INTO public.services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  display_order, is_active, source_site
) VALUES (
  'Auditoría de Ayudas Autonómicas',
  'Regional Grants Audit',
  'Auditoria d''Ajudes Autonòmiques',
  'auditoria-subvenciones-autonomicas',
  'regional-grants-audit',
  'auditoria-subvencions-autonomiques',
  'Auditoría de justificación de subvenciones autonómicas: ACCIÓ (Cataluña), IVACE (Valencia), SPRI (País Vasco), programas ICEX de internacionalización y ayudas regionales. Conocemos la normativa específica de cada comunidad autónoma.',
  'Justification audit for regional grants: ACCIÓ (Catalonia), IVACE (Valencia), SPRI (Basque Country), ICEX internationalization programs and regional aid. We know each autonomous community''s specific regulations.',
  'Auditoria de justificació de subvencions autonòmiques: ACCIÓ (Catalunya), IVACE (València), SPRI (País Basc), programes ICEX d''internacionalització i ajudes regionals. Coneixem la normativa específica de cada comunitat autònoma.',
  'Auditoría de Cumplimiento', 'Compliance Audit', 'Auditoria de Compliment',
  'MapPin',
  ARRAY['Conocimiento de normativa autonómica específica', 'Verificación de requisitos regionales', 'Control de documentación según CCAA', 'Revisión de bases reguladoras específicas', 'Coordinación con organismos intermedios', 'Informe adaptado a cada programa'],
  ARRAY['Specific regional regulation knowledge', 'Regional requirements verification', 'Documentation control per region', 'Specific regulatory bases review', 'Coordination with intermediate bodies', 'Report adapted to each program'],
  ARRAY['Coneixement de normativa autonòmica específica', 'Verificació de requisits regionals', 'Control de documentació segons CCAA', 'Revisió de bases reguladores específiques', 'Coordinació amb organismes intermedis', 'Informe adaptat a cada programa'],
  ARRAY['Empresas catalanas (ACCIÓ)', 'Empresas valencianas (IVACE)', 'Empresas vascas (SPRI)', 'Empresas exportadoras (ICEX)', 'Pymes con ayudas regionales'],
  ARRAY['Catalan companies (ACCIÓ)', 'Valencian companies (IVACE)', 'Basque companies (SPRI)', 'Exporting companies (ICEX)', 'SMEs with regional grants'],
  ARRAY['Empreses catalanes (ACCIÓ)', 'Empreses valencianes (IVACE)', 'Empreses basques (SPRI)', 'Empreses exportadores (ICEX)', 'Pimes amb ajudes regionals'],
  'Auditoría ACCIÓ, IVACE, SPRI, ICEX | Ayudas Autonómicas',
  'ACCIÓ, IVACE, SPRI, ICEX Audit | Regional Grants',
  'Auditoria ACCIÓ, IVACE, SPRI, ICEX | Ajudes Autonòmiques',
  'Auditoría especializada en subvenciones autonómicas: ACCIÓ, IVACE, SPRI, ICEX. Conocemos la normativa de cada CCAA.',
  'Specialized audit for regional grants: ACCIÓ, IVACE, SPRI, ICEX. We know each region''s regulations.',
  'Auditoria especialitzada en subvencions autonòmiques: ACCIÓ, IVACE, SPRI, ICEX. Coneixem la normativa de cada CCAA.',
  206, true, 'audit'
);