-- Insert 21 Audit Services with complete multilingual content
-- display_order starts at 100 to avoid conflicts with existing services

-- 1. Auditoría de Cuentas Anuales (Obligatoria)
INSERT INTO services (
  name_es, name_en, name_ca,
  slug_es, slug_en, slug_ca,
  description_es, description_en, description_ca,
  area_es, area_en, area_ca,
  icon_name,
  features_es, features_en, features_ca,
  typical_clients_es, typical_clients_en, typical_clients_ca,
  meta_title_es, meta_title_en, meta_title_ca,
  meta_description_es, meta_description_en, meta_description_ca,
  is_active, display_order, source_site
) VALUES (
  'Auditoría de Cuentas Anuales',
  'Annual Accounts Audit',
  'Auditoria de Comptes Anuals',
  'auditoria-cuentas-anuales',
  'annual-accounts-audit',
  'auditoria-comptes-anuals',
  'Auditoría estatutaria de cuentas anuales conforme a la normativa española (NIA-ES) y europea. Verificamos la imagen fiel de sus estados financieros cumpliendo con los requisitos del ICAC y el Registro Mercantil.',
  'Statutory audit of annual accounts in accordance with Spanish (NIA-ES) and European regulations. We verify the true and fair view of your financial statements in compliance with ICAC and Commercial Registry requirements.',
  'Auditoria estatutària de comptes anuals conforme a la normativa espanyola (NIA-ES) i europea. Verifiquem la imatge fidel dels seus estats financers complint amb els requisits de l''ICAC i el Registre Mercantil.',
  'Auditoría Financiera',
  'Financial Audit',
  'Auditoria Financera',
  'FileCheck',
  ARRAY['Verificación de estados financieros', 'Informe de auditoría para el Registro Mercantil', 'Carta de recomendaciones de control interno', 'Cumplimiento NIA-ES e ICAC', 'Revisión de memoria y gestión'],
  ARRAY['Financial statements verification', 'Audit report for Commercial Registry', 'Internal control recommendations letter', 'NIA-ES and ICAC compliance', 'Notes and management review'],
  ARRAY['Verificació d''estats financers', 'Informe d''auditoria per al Registre Mercantil', 'Carta de recomanacions de control intern', 'Compliment NIA-ES i ICAC', 'Revisió de memòria i gestió'],
  ARRAY['Empresas obligadas a auditar (Art. 263 TRLSC)', 'Sociedades cotizadas', 'Entidades de interés público', 'Empresas que superen umbrales legales'],
  ARRAY['Companies required to audit (Art. 263 TRLSC)', 'Listed companies', 'Public interest entities', 'Companies exceeding legal thresholds'],
  ARRAY['Empreses obligades a auditar (Art. 263 TRLSC)', 'Societats cotitzades', 'Entitats d''interès públic', 'Empreses que superin llindars legals'],
  'Auditoría de Cuentas Anuales | Navarro Auditores Barcelona',
  'Annual Accounts Audit | Navarro Auditors Barcelona',
  'Auditoria de Comptes Anuals | Navarro Auditors Barcelona',
  'Auditoría estatutaria de cuentas anuales conforme a NIA-ES. Auditores inscritos en el ROAC con más de 25 años de experiencia en Barcelona.',
  'Statutory audit of annual accounts in accordance with NIA-ES. ROAC registered auditors with over 25 years of experience in Barcelona.',
  'Auditoria estatutària de comptes anuals conforme a NIA-ES. Auditors inscrits al ROAC amb més de 25 anys d''experiència a Barcelona.',
  true, 100, 'navarro_asesores'
),

-- 2. Auditoría de Cuentas Consolidadas
(
  'Auditoría de Cuentas Consolidadas',
  'Consolidated Accounts Audit',
  'Auditoria de Comptes Consolidats',
  'auditoria-cuentas-consolidadas',
  'consolidated-accounts-audit',
  'auditoria-comptes-consolidats',
  'Auditoría de grupos empresariales y cuentas consolidadas. Coordinamos con auditores de filiales nacionales e internacionales para emitir una opinión de auditoría sobre el grupo.',
  'Audit of business groups and consolidated accounts. We coordinate with auditors of national and international subsidiaries to issue an audit opinion on the group.',
  'Auditoria de grups empresarials i comptes consolidats. Coordinem amb auditors de filials nacionals i internacionals per emetre una opinió d''auditoria sobre el grup.',
  'Auditoría Financiera',
  'Financial Audit',
  'Auditoria Financera',
  'Files',
  ARRAY['Consolidación de estados financieros', 'Coordinación con auditores de componentes', 'Eliminación de operaciones intergrupo', 'Conversión de moneda extranjera', 'Informe consolidado para el grupo'],
  ARRAY['Consolidation of financial statements', 'Coordination with component auditors', 'Elimination of intergroup transactions', 'Foreign currency conversion', 'Consolidated report for the group'],
  ARRAY['Consolidació d''estats financers', 'Coordinació amb auditors de components', 'Eliminació d''operacions intergrup', 'Conversió de moneda estrangera', 'Informe consolidat per al grup'],
  ARRAY['Grupos empresariales', 'Holdings familiares', 'Multinacionales con filiales en España', 'Grupos obligados a consolidar'],
  ARRAY['Business groups', 'Family holdings', 'Multinationals with subsidiaries in Spain', 'Groups required to consolidate'],
  ARRAY['Grups empresarials', 'Holdings familiars', 'Multinacionals amb filials a Espanya', 'Grups obligats a consolidar'],
  'Auditoría de Cuentas Consolidadas | Grupos Empresariales',
  'Consolidated Accounts Audit | Business Groups',
  'Auditoria de Comptes Consolidats | Grups Empresarials',
  'Auditoría de cuentas consolidadas para grupos empresariales. Coordinación internacional y cumplimiento normativo.',
  'Consolidated accounts audit for business groups. International coordination and regulatory compliance.',
  'Auditoria de comptes consolidats per a grups empresarials. Coordinació internacional i compliment normatiu.',
  true, 101, 'navarro_asesores'
),

-- 3. Auditoría de Subvenciones Públicas
(
  'Auditoría de Subvenciones Públicas',
  'Public Grants Audit',
  'Auditoria de Subvencions Públiques',
  'auditoria-subvenciones-publicas',
  'public-grants-audit',
  'auditoria-subvencions-publiques',
  'Auditoría y justificación de subvenciones públicas (CDTI, ACCIÓ, fondos europeos). Verificamos el cumplimiento de las bases reguladoras y la correcta aplicación de los fondos recibidos.',
  'Audit and justification of public grants (CDTI, ACCIÓ, European funds). We verify compliance with regulatory bases and correct application of received funds.',
  'Auditoria i justificació de subvencions públiques (CDTI, ACCIÓ, fons europeus). Verifiquem el compliment de les bases reguladores i la correcta aplicació dels fons rebuts.',
  'Auditoría de Cumplimiento',
  'Compliance Audit',
  'Auditoria de Compliment',
  'Landmark',
  ARRAY['Verificación de gastos elegibles', 'Informe de auditor independiente', 'Cumplimiento de bases reguladoras', 'Justificación técnica y económica', 'Preparación para controles oficiales'],
  ARRAY['Verification of eligible expenses', 'Independent auditor report', 'Compliance with regulatory bases', 'Technical and economic justification', 'Preparation for official controls'],
  ARRAY['Verificació de despeses elegibles', 'Informe d''auditor independent', 'Compliment de bases reguladores', 'Justificació tècnica i econòmica', 'Preparació per a controls oficials'],
  ARRAY['Empresas con subvenciones CDTI', 'Beneficiarios de fondos europeos', 'Proyectos I+D+i subvencionados', 'ONGs con financiación pública'],
  ARRAY['Companies with CDTI grants', 'European funds beneficiaries', 'Subsidized R&D projects', 'NGOs with public funding'],
  ARRAY['Empreses amb subvencions CDTI', 'Beneficiaris de fons europeus', 'Projectes R+D+i subvencionats', 'ONGs amb finançament públic'],
  'Auditoría de Subvenciones | CDTI, Fondos Europeos',
  'Public Grants Audit | CDTI, European Funds',
  'Auditoria de Subvencions | CDTI, Fons Europeus',
  'Auditoría y justificación de subvenciones públicas. Especialistas en CDTI, ACCIÓ y fondos europeos.',
  'Audit and justification of public grants. Specialists in CDTI, ACCIÓ and European funds.',
  'Auditoria i justificació de subvencions públiques. Especialistes en CDTI, ACCIÓ i fons europeus.',
  true, 102, 'navarro_asesores'
),

-- 4. Auditoría para Contratos Públicos
(
  'Auditoría para Contratos Públicos',
  'Public Contracts Audit',
  'Auditoria per a Contractes Públics',
  'auditoria-contratos-publicos',
  'public-contracts-audit',
  'auditoria-contractes-publics',
  'Auditoría de cuentas requerida para licitaciones y contratos con la Administración Pública. Cumplimos con los requisitos de clasificación empresarial y solvencia económica.',
  'Audit of accounts required for tenders and contracts with Public Administration. We comply with business classification and economic solvency requirements.',
  'Auditoria de comptes requerida per a licitacions i contractes amb l''Administració Pública. Complim amb els requisits de classificació empresarial i solvència econòmica.',
  'Auditoría de Cumplimiento',
  'Compliance Audit',
  'Auditoria de Compliment',
  'FileSignature',
  ARRAY['Informe para clasificación empresarial', 'Acreditación de solvencia económica', 'Cumplimiento Ley de Contratos del Sector Público', 'Certificados para licitaciones', 'Auditoría de ejecución de contratos'],
  ARRAY['Report for business classification', 'Economic solvency accreditation', 'Public Sector Contracts Law compliance', 'Certificates for tenders', 'Contract execution audit'],
  ARRAY['Informe per a classificació empresarial', 'Acreditació de solvència econòmica', 'Compliment Llei de Contractes del Sector Públic', 'Certificats per a licitacions', 'Auditoria d''execució de contractes'],
  ARRAY['Contratistas del sector público', 'Empresas de construcción', 'Proveedores de la Administración', 'Concesionarios de servicios públicos'],
  ARRAY['Public sector contractors', 'Construction companies', 'Administration suppliers', 'Public service concessionaires'],
  ARRAY['Contractistes del sector públic', 'Empreses de construcció', 'Proveïdors de l''Administració', 'Concessionaris de serveis públics'],
  'Auditoría Contratos Públicos | Licitaciones',
  'Public Contracts Audit | Tenders',
  'Auditoria Contractes Públics | Licitacions',
  'Auditoría de cuentas para licitaciones públicas. Clasificación empresarial y solvencia económica.',
  'Accounts audit for public tenders. Business classification and economic solvency.',
  'Auditoria de comptes per a licitacions públiques. Classificació empresarial i solvència econòmica.',
  true, 103, 'navarro_asesores'
),

-- 5. Auditoría de Fundaciones y ENL
(
  'Auditoría de Fundaciones y Entidades No Lucrativas',
  'Foundations and Non-Profit Entities Audit',
  'Auditoria de Fundacions i Entitats No Lucratives',
  'auditoria-fundaciones-entidades-no-lucrativas',
  'foundations-non-profit-entities-audit',
  'auditoria-fundacions-entitats-no-lucratives',
  'Auditoría especializada en fundaciones, asociaciones y entidades del Tercer Sector. Cumplimos con los requisitos del Protectorado y la normativa específica de ENL.',
  'Specialized audit for foundations, associations and Third Sector entities. We comply with Protectorate requirements and specific ENL regulations.',
  'Auditoria especialitzada en fundacions, associacions i entitats del Tercer Sector. Complim amb els requisits del Protectorat i la normativa específica d''ENL.',
  'Auditoría de Cumplimiento',
  'Compliance Audit',
  'Auditoria de Compliment',
  'Heart',
  ARRAY['Plan de actuación y liquidación presupuestaria', 'Informe para el Protectorado', 'Verificación de fines fundacionales', 'Cumplimiento Ley de Fundaciones', 'Transparencia y buen gobierno'],
  ARRAY['Action plan and budget settlement', 'Report for the Protectorate', 'Verification of foundational purposes', 'Foundations Law compliance', 'Transparency and good governance'],
  ARRAY['Pla d''actuació i liquidació pressupostària', 'Informe per al Protectorat', 'Verificació de fins fundacionals', 'Compliment Llei de Fundacions', 'Transparència i bon govern'],
  ARRAY['Fundaciones privadas', 'Asociaciones de utilidad pública', 'ONGs y entidades del Tercer Sector', 'Fundaciones empresariales'],
  ARRAY['Private foundations', 'Public utility associations', 'NGOs and Third Sector entities', 'Corporate foundations'],
  ARRAY['Fundacions privades', 'Associacions d''utilitat pública', 'ONGs i entitats del Tercer Sector', 'Fundacions empresarials'],
  'Auditoría Fundaciones y ENL | Tercer Sector',
  'Foundations and Non-Profit Audit | Third Sector',
  'Auditoria Fundacions i ENL | Tercer Sector',
  'Auditoría de fundaciones y entidades no lucrativas. Especialistas en Tercer Sector y Protectorado.',
  'Audit of foundations and non-profit entities. Specialists in Third Sector and Protectorate.',
  'Auditoria de fundacions i entitats no lucratives. Especialistes en Tercer Sector i Protectorat.',
  true, 104, 'navarro_asesores'
),

-- 6. Auditoría de Cooperativas
(
  'Auditoría de Cooperativas',
  'Cooperatives Audit',
  'Auditoria de Cooperatives',
  'auditoria-cooperativas',
  'cooperatives-audit',
  'auditoria-cooperatives',
  'Auditoría especializada en sociedades cooperativas conforme a la Ley de Cooperativas. Verificamos la dotación a fondos obligatorios y el cumplimiento de principios cooperativos.',
  'Specialized audit for cooperative societies in accordance with the Cooperatives Law. We verify mandatory fund allocations and compliance with cooperative principles.',
  'Auditoria especialitzada en societats cooperatives conforme a la Llei de Cooperatives. Verifiquem la dotació a fons obligatoris i el compliment de principis cooperatius.',
  'Auditoría de Cumplimiento',
  'Compliance Audit',
  'Auditoria de Compliment',
  'Users',
  ARRAY['Dotación a fondos obligatorios (FRO, FEP)', 'Cumplimiento principios cooperativos', 'Informe para Registro de Cooperativas', 'Verificación de operaciones con socios', 'Retornos cooperativos'],
  ARRAY['Mandatory fund allocations (FRO, FEP)', 'Cooperative principles compliance', 'Report for Cooperatives Registry', 'Verification of operations with members', 'Cooperative returns'],
  ARRAY['Dotació a fons obligatoris (FRO, FEP)', 'Compliment principis cooperatius', 'Informe per a Registre de Cooperatives', 'Verificació d''operacions amb socis', 'Retorns cooperatius'],
  ARRAY['Cooperativas de trabajo asociado', 'Cooperativas agrarias', 'Cooperativas de viviendas', 'Cooperativas de servicios'],
  ARRAY['Worker cooperatives', 'Agricultural cooperatives', 'Housing cooperatives', 'Service cooperatives'],
  ARRAY['Cooperatives de treball associat', 'Cooperatives agràries', 'Cooperatives d''habitatges', 'Cooperatives de serveis'],
  'Auditoría de Cooperativas | Especialistas',
  'Cooperatives Audit | Specialists',
  'Auditoria de Cooperatives | Especialistes',
  'Auditoría de cooperativas conforme a la Ley de Cooperativas. Fondos obligatorios y principios cooperativos.',
  'Cooperatives audit in accordance with Cooperatives Law. Mandatory funds and cooperative principles.',
  'Auditoria de cooperatives conforme a la Llei de Cooperatives. Fons obligatoris i principis cooperatius.',
  true, 105, 'navarro_asesores'
),

-- 7. Verificación CSRD/ESRS (ESG)
(
  'Verificación CSRD/ESRS',
  'CSRD/ESRS Verification',
  'Verificació CSRD/ESRS',
  'verificacion-csrd-esrs-sostenibilidad',
  'csrd-esrs-sustainability-verification',
  'verificacio-csrd-esrs-sostenibilitat',
  'Verificación de informes de sostenibilidad conforme a la Directiva CSRD y los Estándares ESRS. Preparamos a su empresa para los nuevos requisitos de reporting ESG obligatorio.',
  'Verification of sustainability reports in accordance with the CSRD Directive and ESRS Standards. We prepare your company for the new mandatory ESG reporting requirements.',
  'Verificació d''informes de sostenibilitat conforme a la Directiva CSRD i els Estàndards ESRS. Preparem la seva empresa per als nous requisits de reporting ESG obligatori.',
  'Auditoría ESG',
  'ESG Audit',
  'Auditoria ESG',
  'Leaf',
  ARRAY['Verificación de estados de sostenibilidad', 'Análisis de doble materialidad', 'Cumplimiento ESRS (E1-E5, S1-S4, G1)', 'Gap analysis CSRD', 'Formación al equipo directivo'],
  ARRAY['Sustainability statements verification', 'Double materiality analysis', 'ESRS compliance (E1-E5, S1-S4, G1)', 'CSRD gap analysis', 'Management team training'],
  ARRAY['Verificació d''estats de sostenibilitat', 'Anàlisi de doble materialitat', 'Compliment ESRS (E1-E5, S1-S4, G1)', 'Gap analysis CSRD', 'Formació a l''equip directiu'],
  ARRAY['Grandes empresas (+250 empleados)', 'Empresas cotizadas', 'Filiales de grupos europeos', 'Empresas en cadena de valor de obligadas'],
  ARRAY['Large companies (+250 employees)', 'Listed companies', 'Subsidiaries of European groups', 'Companies in supply chain of obligated entities'],
  ARRAY['Grans empreses (+250 empleats)', 'Empreses cotitzades', 'Filials de grups europeus', 'Empreses en cadena de valor d''obligades'],
  'Verificación CSRD/ESRS | Sostenibilidad Corporativa',
  'CSRD/ESRS Verification | Corporate Sustainability',
  'Verificació CSRD/ESRS | Sostenibilitat Corporativa',
  'Verificación de informes de sostenibilidad CSRD/ESRS. Preparamos su empresa para el reporting ESG obligatorio.',
  'CSRD/ESRS sustainability report verification. We prepare your company for mandatory ESG reporting.',
  'Verificació d''informes de sostenibilitat CSRD/ESRS. Preparem la seva empresa per al reporting ESG obligatori.',
  true, 106, 'navarro_asesores'
),

-- 8. Auditoría de Huella de Carbono
(
  'Auditoría de Huella de Carbono',
  'Carbon Footprint Audit',
  'Auditoria de Petjada de Carboni',
  'auditoria-huella-carbono',
  'carbon-footprint-audit',
  'auditoria-petjada-carboni',
  'Verificación de la huella de carbono corporativa (Alcance 1, 2 y 3) conforme a ISO 14064 y GHG Protocol. Validamos sus cálculos de emisiones para inscripción en registros oficiales.',
  'Verification of corporate carbon footprint (Scope 1, 2 and 3) in accordance with ISO 14064 and GHG Protocol. We validate your emissions calculations for registration in official registries.',
  'Verificació de la petjada de carboni corporativa (Abast 1, 2 i 3) conforme a ISO 14064 i GHG Protocol. Validem els seus càlculs d''emissions per a inscripció en registres oficials.',
  'Auditoría ESG',
  'ESG Audit',
  'Auditoria ESG',
  'Cloud',
  ARRAY['Verificación Alcance 1, 2 y 3', 'Cumplimiento ISO 14064', 'Validación GHG Protocol', 'Inscripción en registro MITECO', 'Plan de reducción de emisiones'],
  ARRAY['Scope 1, 2 and 3 verification', 'ISO 14064 compliance', 'GHG Protocol validation', 'MITECO registry registration', 'Emissions reduction plan'],
  ARRAY['Verificació Abast 1, 2 i 3', 'Compliment ISO 14064', 'Validació GHG Protocol', 'Inscripció en registre MITECO', 'Pla de reducció d''emissions'],
  ARRAY['Empresas con objetivos Net Zero', 'Participantes en RCDE-UE', 'Empresas con requisitos de cadena de suministro', 'Organizaciones comprometidas con sostenibilidad'],
  ARRAY['Companies with Net Zero targets', 'EU ETS participants', 'Companies with supply chain requirements', 'Organizations committed to sustainability'],
  ARRAY['Empreses amb objectius Net Zero', 'Participants en RCDE-UE', 'Empreses amb requisits de cadena de subministrament', 'Organitzacions compromeses amb sostenibilitat'],
  'Auditoría Huella de Carbono | ISO 14064',
  'Carbon Footprint Audit | ISO 14064',
  'Auditoria Petjada de Carboni | ISO 14064',
  'Verificación de huella de carbono conforme a ISO 14064 y GHG Protocol. Alcance 1, 2 y 3.',
  'Carbon footprint verification in accordance with ISO 14064 and GHG Protocol. Scope 1, 2 and 3.',
  'Verificació de petjada de carboni conforme a ISO 14064 i GHG Protocol. Abast 1, 2 i 3.',
  true, 107, 'navarro_asesores'
),

-- 9. Verificación Taxonomía UE
(
  'Verificación Taxonomía UE',
  'EU Taxonomy Verification',
  'Verificació Taxonomia UE',
  'verificacion-taxonomia-ue',
  'eu-taxonomy-verification',
  'verificacio-taxonomia-ue',
  'Verificación de la alineación de actividades económicas con la Taxonomía de la UE. Evaluamos el cumplimiento de criterios técnicos de selección y principio DNSH.',
  'Verification of economic activities alignment with EU Taxonomy. We evaluate compliance with technical screening criteria and DNSH principle.',
  'Verificació de l''alineació d''activitats econòmiques amb la Taxonomia de la UE. Avaluem el compliment de criteris tècnics de selecció i principi DNSH.',
  'Auditoría ESG',
  'ESG Audit',
  'Auditoria ESG',
  'TreeDeciduous',
  ARRAY['Análisis de elegibilidad de actividades', 'Verificación de criterios técnicos', 'Evaluación principio DNSH', 'Salvaguardas sociales mínimas', 'Reporting para inversores'],
  ARRAY['Activity eligibility analysis', 'Technical criteria verification', 'DNSH principle evaluation', 'Minimum social safeguards', 'Investor reporting'],
  ARRAY['Anàlisi d''elegibilitat d''activitats', 'Verificació de criteris tècnics', 'Avaluació principi DNSH', 'Salvaguardes socials mínimes', 'Reporting per a inversors'],
  ARRAY['Empresas obligadas por CSRD', 'Fondos de inversión sostenible', 'Empresas buscando financiación verde', 'Entidades financieras'],
  ARRAY['Companies obligated by CSRD', 'Sustainable investment funds', 'Companies seeking green financing', 'Financial entities'],
  ARRAY['Empreses obligades per CSRD', 'Fons d''inversió sostenible', 'Empreses buscant finançament verd', 'Entitats financeres'],
  'Verificación Taxonomía UE | Finanzas Sostenibles',
  'EU Taxonomy Verification | Sustainable Finance',
  'Verificació Taxonomia UE | Finances Sostenibles',
  'Verificación de alineación con la Taxonomía de la UE. Criterios técnicos y principio DNSH.',
  'EU Taxonomy alignment verification. Technical criteria and DNSH principle.',
  'Verificació d''alineació amb la Taxonomia de la UE. Criteris tècnics i principi DNSH.',
  true, 108, 'navarro_asesores'
),

-- 10. Auditoría de Información No Financiera (EINF)
(
  'Auditoría de Información No Financiera',
  'Non-Financial Information Audit',
  'Auditoria d''Informació No Financera',
  'auditoria-informacion-no-financiera-einf',
  'non-financial-information-audit-nfrd',
  'auditoria-informacio-no-financera-einf',
  'Verificación del Estado de Información No Financiera (EINF) conforme a la Ley 11/2018. Revisamos indicadores ESG, políticas de diversidad, derechos humanos y anticorrupción.',
  'Verification of Non-Financial Information Statement (NFIS) in accordance with Law 11/2018. We review ESG indicators, diversity policies, human rights and anti-corruption.',
  'Verificació de l''Estat d''Informació No Financera (EINF) conforme a la Llei 11/2018. Revisem indicadors ESG, polítiques de diversitat, drets humans i anticorrupció.',
  'Auditoría ESG',
  'ESG Audit',
  'Auditoria ESG',
  'BarChart3',
  ARRAY['Verificación EINF Ley 11/2018', 'Indicadores medioambientales y sociales', 'Políticas de diversidad e igualdad', 'Derechos humanos y cadena de suministro', 'Medidas anticorrupción'],
  ARRAY['NFIS verification Law 11/2018', 'Environmental and social indicators', 'Diversity and equality policies', 'Human rights and supply chain', 'Anti-corruption measures'],
  ARRAY['Verificació EINF Llei 11/2018', 'Indicadors mediambientals i socials', 'Polítiques de diversitat i igualtat', 'Drets humans i cadena de subministrament', 'Mesures anticorrupció'],
  ARRAY['Empresas +500 empleados (hasta CSRD)', 'Sociedades de interés público', 'Empresas cotizadas', 'Grupos consolidados grandes'],
  ARRAY['Companies +500 employees (until CSRD)', 'Public interest entities', 'Listed companies', 'Large consolidated groups'],
  ARRAY['Empreses +500 empleats (fins CSRD)', 'Societats d''interès públic', 'Empreses cotitzades', 'Grups consolidats grans'],
  'Auditoría EINF | Información No Financiera',
  'NFIS Audit | Non-Financial Information',
  'Auditoria EINF | Informació No Financera',
  'Verificación del Estado de Información No Financiera conforme a Ley 11/2018. Indicadores ESG.',
  'Non-Financial Information Statement verification in accordance with Law 11/2018. ESG indicators.',
  'Verificació de l''Estat d''Informació No Financera conforme a Llei 11/2018. Indicadors ESG.',
  true, 109, 'navarro_asesores'
),

-- 11. Due Diligence Financiera
(
  'Due Diligence Financiera',
  'Financial Due Diligence',
  'Due Diligence Financera',
  'due-diligence-financiera',
  'financial-due-diligence',
  'due-diligence-financera',
  'Análisis financiero exhaustivo para operaciones de M&A, inversiones y reestructuraciones. Identificamos riesgos ocultos, ajustes al EBITDA y calidad de los beneficios.',
  'Comprehensive financial analysis for M&A transactions, investments and restructurings. We identify hidden risks, EBITDA adjustments and earnings quality.',
  'Anàlisi financera exhaustiva per a operacions de M&A, inversions i reestructuracions. Identifiquem riscos ocults, ajustos a l''EBITDA i qualitat dels beneficis.',
  'Auditoría Transaccional',
  'Transaction Audit',
  'Auditoria Transaccional',
  'Search',
  ARRAY['Quality of Earnings (QoE)', 'Análisis de EBITDA normalizado', 'Working capital y Net Debt', 'Identificación de contingencias', 'Red flags y deal breakers'],
  ARRAY['Quality of Earnings (QoE)', 'Normalized EBITDA analysis', 'Working capital and Net Debt', 'Contingencies identification', 'Red flags and deal breakers'],
  ARRAY['Quality of Earnings (QoE)', 'Anàlisi d''EBITDA normalitzat', 'Working capital i Net Debt', 'Identificació de contingències', 'Red flags i deal breakers'],
  ARRAY['Fondos de Private Equity', 'Family Offices', 'Compradores corporativos', 'Inversores estratégicos'],
  ARRAY['Private Equity funds', 'Family Offices', 'Corporate buyers', 'Strategic investors'],
  ARRAY['Fons de Private Equity', 'Family Offices', 'Compradors corporatius', 'Inversors estratègics'],
  'Due Diligence Financiera | M&A',
  'Financial Due Diligence | M&A',
  'Due Diligence Financera | M&A',
  'Due diligence financiera para operaciones M&A. Quality of Earnings, EBITDA y contingencias.',
  'Financial due diligence for M&A transactions. Quality of Earnings, EBITDA and contingencies.',
  'Due diligence financera per a operacions M&A. Quality of Earnings, EBITDA i contingències.',
  true, 110, 'navarro_asesores'
),

-- 12. Due Diligence Fiscal
(
  'Due Diligence Fiscal',
  'Tax Due Diligence',
  'Due Diligence Fiscal',
  'due-diligence-fiscal',
  'tax-due-diligence',
  'due-diligence-fiscal',
  'Revisión exhaustiva de contingencias fiscales en operaciones de M&A. Analizamos riesgos en IVA, Impuesto sobre Sociedades, precios de transferencia y obligaciones formales.',
  'Comprehensive review of tax contingencies in M&A transactions. We analyze risks in VAT, Corporate Tax, transfer pricing and formal obligations.',
  'Revisió exhaustiva de contingències fiscals en operacions de M&A. Analitzem riscos en IVA, Impost sobre Societats, preus de transferència i obligacions formals.',
  'Auditoría Transaccional',
  'Transaction Audit',
  'Auditoria Transaccional',
  'Calculator',
  ARRAY['Contingencias en Impuesto sobre Sociedades', 'Riesgos en IVA e impuestos indirectos', 'Precios de transferencia', 'Tax attributes y créditos fiscales', 'Estructura post-deal óptima'],
  ARRAY['Corporate Tax contingencies', 'VAT and indirect tax risks', 'Transfer pricing', 'Tax attributes and credits', 'Optimal post-deal structure'],
  ARRAY['Contingències en Impost sobre Societats', 'Riscos en IVA i impostos indirectes', 'Preus de transferència', 'Tax attributes i crèdits fiscals', 'Estructura post-deal òptima'],
  ARRAY['Fondos de inversión', 'Compradores en M&A', 'Vendedores preparando exit', 'Asesores de transacciones'],
  ARRAY['Investment funds', 'M&A buyers', 'Sellers preparing exit', 'Transaction advisors'],
  ARRAY['Fons d''inversió', 'Compradors en M&A', 'Venedors preparant exit', 'Assessors de transaccions'],
  'Due Diligence Fiscal | Contingencias Tributarias',
  'Tax Due Diligence | Tax Contingencies',
  'Due Diligence Fiscal | Contingències Tributàries',
  'Due diligence fiscal para M&A. Contingencias tributarias, IVA y precios de transferencia.',
  'Tax due diligence for M&A. Tax contingencies, VAT and transfer pricing.',
  'Due diligence fiscal per a M&A. Contingències tributàries, IVA i preus de transferència.',
  true, 111, 'navarro_asesores'
),

-- 13. Vendor Due Diligence
(
  'Vendor Due Diligence',
  'Vendor Due Diligence',
  'Vendor Due Diligence',
  'vendor-due-diligence',
  'vendor-due-diligence',
  'vendor-due-diligence',
  'Informe de due diligence preparado por el vendedor para facilitar el proceso de venta. Maximiza el valor de la transacción y acelera el cierre del deal.',
  'Due diligence report prepared by the seller to facilitate the sale process. Maximizes transaction value and accelerates deal closing.',
  'Informe de due diligence preparat pel venedor per facilitar el procés de venda. Maximitza el valor de la transacció i accelera el tancament del deal.',
  'Auditoría Transaccional',
  'Transaction Audit',
  'Auditoria Transaccional',
  'UserCheck',
  ARRAY['Informe independiente para compradores', 'Identificación proactiva de issues', 'Data room estructurado', 'Narrativa de equity story', 'Maximización del valor de venta'],
  ARRAY['Independent report for buyers', 'Proactive issue identification', 'Structured data room', 'Equity story narrative', 'Sale value maximization'],
  ARRAY['Informe independent per a compradors', 'Identificació proactiva d''issues', 'Data room estructurat', 'Narrativa d''equity story', 'Maximització del valor de venda'],
  ARRAY['Empresarios vendiendo su compañía', 'Private Equity en exit', 'Familias en proceso de sucesión', 'Desinversiones corporativas'],
  ARRAY['Business owners selling their company', 'Private Equity in exit', 'Families in succession process', 'Corporate divestitures'],
  ARRAY['Empresaris venent la seva companyia', 'Private Equity en exit', 'Famílies en procés de successió', 'Desinversions corporatives'],
  'Vendor Due Diligence | Preparación para Venta',
  'Vendor Due Diligence | Sale Preparation',
  'Vendor Due Diligence | Preparació per a Venda',
  'Vendor due diligence para vendedores. Maximiza valor y acelera el proceso de venta.',
  'Vendor due diligence for sellers. Maximize value and accelerate the sale process.',
  'Vendor due diligence per a venedors. Maximitza valor i accelera el procés de venda.',
  true, 112, 'navarro_asesores'
),

-- 14. Due Diligence Operativa
(
  'Due Diligence Operativa',
  'Operational Due Diligence',
  'Due Diligence Operativa',
  'due-diligence-operativa',
  'operational-due-diligence',
  'due-diligence-operativa',
  'Análisis de operaciones, procesos y eficiencia del negocio en contexto M&A. Identificamos oportunidades de mejora, sinergias y riesgos operativos.',
  'Analysis of operations, processes and business efficiency in M&A context. We identify improvement opportunities, synergies and operational risks.',
  'Anàlisi d''operacions, processos i eficiència del negoci en context M&A. Identifiquem oportunitats de millora, sinergies i riscos operatius.',
  'Auditoría Transaccional',
  'Transaction Audit',
  'Auditoria Transaccional',
  'Settings',
  ARRAY['Análisis de procesos clave', 'Identificación de sinergias', 'Evaluación de management', 'Riesgos de integración', 'Plan de 100 días post-deal'],
  ARRAY['Key processes analysis', 'Synergies identification', 'Management evaluation', 'Integration risks', '100-day post-deal plan'],
  ARRAY['Anàlisi de processos clau', 'Identificació de sinergies', 'Avaluació de management', 'Riscos d''integració', 'Pla de 100 dies post-deal'],
  ARRAY['Private Equity operacionales', 'Compradores estratégicos', 'Empresas en proceso de integración', 'Carve-outs y spin-offs'],
  ARRAY['Operational Private Equity', 'Strategic buyers', 'Companies in integration process', 'Carve-outs and spin-offs'],
  ARRAY['Private Equity operacionals', 'Compradors estratègics', 'Empreses en procés d''integració', 'Carve-outs i spin-offs'],
  'Due Diligence Operativa | Sinergias',
  'Operational Due Diligence | Synergies',
  'Due Diligence Operativa | Sinergies',
  'Due diligence operativa para M&A. Sinergias, eficiencia y plan de integración.',
  'Operational due diligence for M&A. Synergies, efficiency and integration plan.',
  'Due diligence operativa per a M&A. Sinergies, eficiència i pla d''integració.',
  true, 113, 'navarro_asesores'
),

-- 15. Outsourcing de Auditoría Interna
(
  'Outsourcing de Auditoría Interna',
  'Internal Audit Outsourcing',
  'Outsourcing d''Auditoria Interna',
  'outsourcing-auditoria-interna',
  'internal-audit-outsourcing',
  'outsourcing-auditoria-interna',
  'Externalización total o parcial de la función de auditoría interna. Aportamos independencia, metodología y recursos especializados sin costes fijos de estructura.',
  'Total or partial outsourcing of the internal audit function. We provide independence, methodology and specialized resources without fixed structural costs.',
  'Externalització total o parcial de la funció d''auditoria interna. Aportem independència, metodologia i recursos especialitzats sense costos fixos d''estructura.',
  'Auditoría Interna',
  'Internal Audit',
  'Auditoria Interna',
  'ShieldCheck',
  ARRAY['Plan anual de auditoría interna', 'Equipo especializado bajo demanda', 'Reporting al Comité de Auditoría', 'Metodología basada en riesgos', 'Seguimiento de recomendaciones'],
  ARRAY['Annual internal audit plan', 'Specialized team on demand', 'Audit Committee reporting', 'Risk-based methodology', 'Recommendations follow-up'],
  ARRAY['Pla anual d''auditoria interna', 'Equip especialitzat sota demanda', 'Reporting al Comitè d''Auditoria', 'Metodologia basada en riscos', 'Seguiment de recomanacions'],
  ARRAY['Empresas sin departamento de auditoría interna', 'Empresas que buscan independencia', 'Pymes en crecimiento', 'Filiales de grupos internacionales'],
  ARRAY['Companies without internal audit department', 'Companies seeking independence', 'Growing SMEs', 'Subsidiaries of international groups'],
  ARRAY['Empreses sense departament d''auditoria interna', 'Empreses que busquen independència', 'Pimes en creixement', 'Filials de grups internacionals'],
  'Outsourcing Auditoría Interna | Flexibilidad',
  'Internal Audit Outsourcing | Flexibility',
  'Outsourcing Auditoria Interna | Flexibilitat',
  'Externalización de auditoría interna. Independencia, metodología y recursos sin costes fijos.',
  'Internal audit outsourcing. Independence, methodology and resources without fixed costs.',
  'Externalització d''auditoria interna. Independència, metodologia i recursos sense costos fixos.',
  true, 114, 'navarro_asesores'
),

-- 16. Evaluación de Control Interno (COSO)
(
  'Evaluación de Control Interno (COSO)',
  'Internal Control Evaluation (COSO)',
  'Avaluació de Control Intern (COSO)',
  'evaluacion-control-interno-coso',
  'internal-control-evaluation-coso',
  'avaluacio-control-intern-coso',
  'Evaluación del sistema de control interno según el marco COSO. Identificamos debilidades de control, gaps en segregación de funciones y oportunidades de mejora.',
  'Evaluation of internal control system according to COSO framework. We identify control weaknesses, segregation of duties gaps and improvement opportunities.',
  'Avaluació del sistema de control intern segons el marc COSO. Identifiquem debilitats de control, gaps en segregació de funcions i oportunitats de millora.',
  'Auditoría Interna',
  'Internal Audit',
  'Auditoria Interna',
  'Shield',
  ARRAY['Diagnóstico COSO 2013/2017', 'Matriz de riesgos y controles', 'Segregación de funciones', 'Testing de controles clave', 'Plan de remediación'],
  ARRAY['COSO 2013/2017 diagnosis', 'Risks and controls matrix', 'Segregation of duties', 'Key controls testing', 'Remediation plan'],
  ARRAY['Diagnòstic COSO 2013/2017', 'Matriu de riscos i controls', 'Segregació de funcions', 'Testing de controls clau', 'Pla de remediació'],
  ARRAY['Empresas preparando IPO', 'Sociedades cotizadas', 'Empresas con requisitos SOX', 'Organizaciones en crecimiento'],
  ARRAY['Companies preparing IPO', 'Listed companies', 'Companies with SOX requirements', 'Growing organizations'],
  ARRAY['Empreses preparant IPO', 'Societats cotitzades', 'Empreses amb requisits SOX', 'Organitzacions en creixement'],
  'Evaluación Control Interno | Marco COSO',
  'Internal Control Evaluation | COSO Framework',
  'Avaluació Control Intern | Marc COSO',
  'Evaluación de control interno según COSO. Segregación de funciones y matriz de riesgos.',
  'Internal control evaluation according to COSO. Segregation of duties and risk matrix.',
  'Avaluació de control intern segons COSO. Segregació de funcions i matriu de riscos.',
  true, 115, 'navarro_asesores'
),

-- 17. Auditoría de Cumplimiento Normativo
(
  'Auditoría de Cumplimiento Normativo',
  'Regulatory Compliance Audit',
  'Auditoria de Compliment Normatiu',
  'auditoria-cumplimiento-normativo',
  'regulatory-compliance-audit',
  'auditoria-compliment-normatiu',
  'Revisión del cumplimiento de normativas específicas del sector (LOPD, PBC, MiFID, Solvencia). Identificamos gaps y proponemos planes de acción para su remediación.',
  'Review of compliance with sector-specific regulations (GDPR, AML, MiFID, Solvency). We identify gaps and propose action plans for remediation.',
  'Revisió del compliment de normatives específiques del sector (LOPD, PBC, MiFID, Solvència). Identifiquem gaps i proposem plans d''acció per a la seva remediació.',
  'Auditoría Interna',
  'Internal Audit',
  'Auditoria Interna',
  'ClipboardCheck',
  ARRAY['Gap analysis normativo', 'Auditoría LOPD/RGPD', 'Revisión PBC/AML', 'Cumplimiento sectorial', 'Plan de acción priorizado'],
  ARRAY['Regulatory gap analysis', 'GDPR audit', 'AML review', 'Sector compliance', 'Prioritized action plan'],
  ARRAY['Gap analysis normatiu', 'Auditoria LOPD/RGPD', 'Revisió PBC/AML', 'Compliment sectorial', 'Pla d''acció prioritzat'],
  ARRAY['Entidades financieras', 'Empresas de servicios de inversión', 'Sector sanitario', 'Empresas con datos personales sensibles'],
  ARRAY['Financial entities', 'Investment services companies', 'Healthcare sector', 'Companies with sensitive personal data'],
  ARRAY['Entitats financeres', 'Empreses de serveis d''inversió', 'Sector sanitari', 'Empreses amb dades personals sensibles'],
  'Auditoría Cumplimiento | LOPD, PBC, MiFID',
  'Compliance Audit | GDPR, AML, MiFID',
  'Auditoria Compliment | LOPD, PBC, MiFID',
  'Auditoría de cumplimiento normativo. LOPD, PBC, MiFID y normativa sectorial.',
  'Regulatory compliance audit. GDPR, AML, MiFID and sector regulations.',
  'Auditoria de compliment normatiu. LOPD, PBC, MiFID i normativa sectorial.',
  true, 116, 'navarro_asesores'
),

-- 18. Auditoría de Sistemas IT (COBIT)
(
  'Auditoría de Sistemas IT (COBIT)',
  'IT Systems Audit (COBIT)',
  'Auditoria de Sistemes IT (COBIT)',
  'auditoria-sistemas-it-cobit',
  'it-systems-audit-cobit',
  'auditoria-sistemes-it-cobit',
  'Auditoría de controles generales de TI y aplicaciones según COBIT e ITIL. Evaluamos ciberseguridad, continuidad de negocio y gobierno de datos.',
  'Audit of IT general controls and applications according to COBIT and ITIL. We evaluate cybersecurity, business continuity and data governance.',
  'Auditoria de controls generals de TI i aplicacions segons COBIT i ITIL. Avaluem ciberseguretat, continuïtat de negoci i govern de dades.',
  'Auditoría Interna',
  'Internal Audit',
  'Auditoria Interna',
  'Server',
  ARRAY['ITGC - Controles generales TI', 'Auditoría de ciberseguridad', 'Plan de continuidad (BCP/DRP)', 'Gobierno de datos', 'Evaluación de proveedores cloud'],
  ARRAY['ITGC - IT General Controls', 'Cybersecurity audit', 'Continuity plan (BCP/DRP)', 'Data governance', 'Cloud providers evaluation'],
  ARRAY['ITGC - Controls generals TI', 'Auditoria de ciberseguretat', 'Pla de continuïtat (BCP/DRP)', 'Govern de dades', 'Avaluació de proveïdors cloud'],
  ARRAY['Empresas digitales', 'Fintech y Insurtech', 'E-commerce', 'Empresas con sistemas críticos'],
  ARRAY['Digital companies', 'Fintech and Insurtech', 'E-commerce', 'Companies with critical systems'],
  ARRAY['Empreses digitals', 'Fintech i Insurtech', 'E-commerce', 'Empreses amb sistemes crítics'],
  'Auditoría IT | COBIT, Ciberseguridad',
  'IT Audit | COBIT, Cybersecurity',
  'Auditoria IT | COBIT, Ciberseguretat',
  'Auditoría de sistemas IT según COBIT. Controles TI, ciberseguridad y continuidad.',
  'IT systems audit according to COBIT. IT controls, cybersecurity and continuity.',
  'Auditoria de sistemes IT segons COBIT. Controls TI, ciberseguretat i continuïtat.',
  true, 117, 'navarro_asesores'
),

-- 19. Informes Especiales de Auditor
(
  'Informes Especiales de Auditor',
  'Special Auditor Reports',
  'Informes Especials d''Auditor',
  'informes-especiales-auditor',
  'special-auditor-reports',
  'informes-especials-auditor',
  'Informes de auditor para operaciones societarias: ampliaciones de capital, fusiones, escisiones, transformaciones y aportaciones no dinerarias conforme a la LSC.',
  'Auditor reports for corporate transactions: capital increases, mergers, spin-offs, transformations and non-cash contributions in accordance with LSC.',
  'Informes d''auditor per a operacions societàries: ampliacions de capital, fusions, escissions, transformacions i aportacions no dineràries conforme a la LSC.',
  'Informes Especiales',
  'Special Reports',
  'Informes Especials',
  'FileText',
  ARRAY['Informe de ampliación de capital', 'Valoración de aportaciones no dinerarias', 'Proyecto de fusión/escisión', 'Informe de transformación societaria', 'Exclusión del derecho de suscripción'],
  ARRAY['Capital increase report', 'Non-cash contributions valuation', 'Merger/spin-off project', 'Corporate transformation report', 'Subscription rights exclusion'],
  ARRAY['Informe d''ampliació de capital', 'Valoració d''aportacions no dineràries', 'Projecte de fusió/escissió', 'Informe de transformació societària', 'Exclusió del dret de subscripció'],
  ARRAY['Empresas en reestructuración', 'Sociedades en proceso de fusión', 'Start-ups con rondas de inversión', 'Grupos empresariales reorganizándose'],
  ARRAY['Companies in restructuring', 'Companies in merger process', 'Start-ups with investment rounds', 'Business groups reorganizing'],
  ARRAY['Empreses en reestructuració', 'Societats en procés de fusió', 'Start-ups amb rondes d''inversió', 'Grups empresarials reorganitzant-se'],
  'Informes Especiales Auditor | Fusiones, Capital',
  'Special Auditor Reports | Mergers, Capital',
  'Informes Especials Auditor | Fusions, Capital',
  'Informes especiales de auditor para operaciones societarias. Fusiones, ampliaciones y aportaciones.',
  'Special auditor reports for corporate transactions. Mergers, capital increases and contributions.',
  'Informes especials d''auditor per a operacions societàries. Fusions, ampliacions i aportacions.',
  true, 118, 'navarro_asesores'
),

-- 20. Procedimientos Acordados (AUP)
(
  'Procedimientos Acordados (AUP)',
  'Agreed-Upon Procedures (AUP)',
  'Procediments Acordats (AUP)',
  'procedimientos-acordados-aup',
  'agreed-upon-procedures-aup',
  'procediments-acordats-aup',
  'Realización de procedimientos específicos acordados con el cliente y emisión de informe de hechos encontrados conforme a ISRS 4400. Sin opinión de auditoría.',
  'Performance of specific procedures agreed with the client and issuance of factual findings report in accordance with ISRS 4400. No audit opinion.',
  'Realització de procediments específics acordats amb el client i emissió d''informe de fets trobats conforme a ISRS 4400. Sense opinió d''auditoria.',
  'Informes Especiales',
  'Special Reports',
  'Informes Especials',
  'FileSearch',
  ARRAY['Procedimientos a medida', 'Informe de hechos encontrados', 'Cumplimiento ISRS 4400', 'Alcance definido por el cliente', 'Verificaciones específicas'],
  ARRAY['Tailored procedures', 'Factual findings report', 'ISRS 4400 compliance', 'Client-defined scope', 'Specific verifications'],
  ARRAY['Procediments a mida', 'Informe de fets trobats', 'Compliment ISRS 4400', 'Abast definit pel client', 'Verificacions específiques'],
  ARRAY['Inversores verificando información', 'Entidades financieras', 'Franquiciadores', 'Administraciones públicas'],
  ARRAY['Investors verifying information', 'Financial entities', 'Franchisors', 'Public administrations'],
  ARRAY['Inversors verificant informació', 'Entitats financeres', 'Franquiciadors', 'Administracions públiques'],
  'Procedimientos Acordados AUP | ISRS 4400',
  'Agreed-Upon Procedures AUP | ISRS 4400',
  'Procediments Acordats AUP | ISRS 4400',
  'Procedimientos acordados (AUP) conforme a ISRS 4400. Verificaciones específicas a medida.',
  'Agreed-upon procedures (AUP) in accordance with ISRS 4400. Tailored specific verifications.',
  'Procediments acordats (AUP) conforme a ISRS 4400. Verificacions específiques a mida.',
  true, 119, 'navarro_asesores'
),

-- 21. Revisión Limitada de Estados Financieros
(
  'Revisión Limitada de Estados Financieros',
  'Limited Review of Financial Statements',
  'Revisió Limitada d''Estats Financers',
  'revision-limitada-estados-financieros',
  'limited-review-financial-statements',
  'revisio-limitada-estats-financers',
  'Revisión limitada (review) de estados financieros conforme a ISRE 2400. Proporciona seguridad limitada a menor coste que una auditoría completa.',
  'Limited review of financial statements in accordance with ISRE 2400. Provides limited assurance at lower cost than a full audit.',
  'Revisió limitada (review) d''estats financers conforme a ISRE 2400. Proporciona seguretat limitada a menor cost que una auditoria completa.',
  'Informes Especiales',
  'Special Reports',
  'Informes Especials',
  'Eye',
  ARRAY['Revisión analítica', 'Indagaciones a la dirección', 'Conclusión de seguridad limitada', 'Cumplimiento ISRE 2400', 'Alternativa a auditoría completa'],
  ARRAY['Analytical review', 'Management inquiries', 'Limited assurance conclusion', 'ISRE 2400 compliance', 'Alternative to full audit'],
  ARRAY['Revisió analítica', 'Indagacions a la direcció', 'Conclusió de seguretat limitada', 'Compliment ISRE 2400', 'Alternativa a auditoria completa'],
  ARRAY['Empresas no obligadas a auditar', 'Start-ups con inversores', 'Filiales de grupos internacionales', 'Empresas buscando credibilidad financiera'],
  ARRAY['Companies not required to audit', 'Start-ups with investors', 'Subsidiaries of international groups', 'Companies seeking financial credibility'],
  ARRAY['Empreses no obligades a auditar', 'Start-ups amb inversors', 'Filials de grups internacionals', 'Empreses buscant credibilitat financera'],
  'Revisión Limitada | ISRE 2400',
  'Limited Review | ISRE 2400',
  'Revisió Limitada | ISRE 2400',
  'Revisión limitada de estados financieros conforme a ISRE 2400. Seguridad limitada a menor coste.',
  'Limited review of financial statements in accordance with ISRE 2400. Limited assurance at lower cost.',
  'Revisió limitada d''estats financers conforme a ISRE 2400. Seguretat limitada a menor cost.',
  true, 120, 'navarro_asesores'
);